-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity em2calo_sub is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    calo_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwIsEM_read : IN STD_LOGIC;
    calo_1_hwIsEM_read : IN STD_LOGIC;
    calo_2_hwIsEM_read : IN STD_LOGIC;
    calo_3_hwIsEM_read : IN STD_LOGIC;
    calo_4_hwIsEM_read : IN STD_LOGIC;
    calo_5_hwIsEM_read : IN STD_LOGIC;
    calo_6_hwIsEM_read : IN STD_LOGIC;
    calo_7_hwIsEM_read : IN STD_LOGIC;
    calo_8_hwIsEM_read : IN STD_LOGIC;
    calo_9_hwIsEM_read : IN STD_LOGIC;
    sumem_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of em2calo_sub is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ptsub_V_fu_504_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_reg_1614 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_fu_510_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_reg_1620 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_reg_1625 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_94_reg_1630 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_1_fu_536_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_1_reg_1635 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_s_fu_542_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_s_reg_1641 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_95_reg_1646 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_96_reg_1651 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_2_fu_568_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_2_reg_1656 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_2_fu_574_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_2_reg_1662 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_97_reg_1667 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_98_reg_1672 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_3_fu_600_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_3_reg_1677 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_3_fu_606_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_3_reg_1683 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_99_reg_1688 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_100_reg_1693 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_4_fu_632_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_4_reg_1698 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_4_fu_638_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_4_reg_1704 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_101_reg_1709 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_102_reg_1714 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_5_fu_664_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_5_reg_1719 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_5_fu_670_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_5_reg_1725 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_103_reg_1730 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_104_reg_1735 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_6_fu_696_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_6_reg_1740 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_6_fu_702_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_6_reg_1746 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_105_reg_1751 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_106_reg_1756 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_7_fu_728_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_7_reg_1761 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_7_fu_734_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_7_reg_1767 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_107_reg_1772 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_108_reg_1777 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_8_fu_760_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_8_reg_1782 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_8_fu_766_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_8_reg_1788 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_109_reg_1793 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_110_reg_1798 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_9_fu_792_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_9_reg_1803 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_9_fu_798_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_9_reg_1809 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_111_reg_1814 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_112_reg_1819 : STD_LOGIC_VECTOR (12 downto 0);
    signal slt_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt_reg_1824 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal slt34_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt34_reg_1829 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt35_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt35_reg_1834 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt36_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt36_reg_1839 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt37_fu_862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt37_reg_1844 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt38_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt38_reg_1849 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt39_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt39_reg_1854 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt40_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt40_reg_1859 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt41_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt41_reg_1864 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt42_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt42_reg_1869 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt43_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt43_reg_1874 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt44_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt44_reg_1879 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt45_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt45_reg_1884 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt46_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt46_reg_1889 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt47_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt47_reg_1894 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt48_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt48_reg_1899 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt49_fu_958_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt49_reg_1904 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt50_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt50_reg_1909 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt51_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt51_reg_1914 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt52_fu_979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt52_reg_1919 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_calo_0_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_0_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_0_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_1_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_2_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_3_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_4_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_5_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_6_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_7_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_8_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_9_hwIsEM_read : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal r_V_fu_824_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_fu_827_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_1_fu_840_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_1_fu_843_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_2_fu_856_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_2_fu_859_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_3_fu_872_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_3_fu_875_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_4_fu_888_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_4_fu_891_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_5_fu_904_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_5_fu_907_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_6_fu_920_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_6_fu_923_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_7_fu_936_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_7_fu_939_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_8_fu_952_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_8_fu_955_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_s_fu_968_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_9_fu_971_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal rev34_fu_989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_994_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_1000_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev36_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1039_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev35_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_1045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev38_fu_1079_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1084_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev37_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_1090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev40_fu_1124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1129_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev39_fu_1119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_1135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev42_fu_1169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1174_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev41_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp63_fu_1180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev44_fu_1214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1219_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev43_fu_1209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp78_fu_1225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev46_fu_1259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1264_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev45_fu_1254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp93_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev48_fu_1304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1309_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev47_fu_1299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp108_fu_1315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev50_fu_1349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1354_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev49_fu_1344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp123_fu_1360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev52_fu_1394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1399_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev51_fu_1389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp138_fu_1405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_out_0_hwPt_V_w_fu_1014_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_1_hwPt_V_w_fu_1059_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_2_hwPt_V_w_fu_1096_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_3_hwPt_V_w_fu_1141_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_4_hwPt_V_w_fu_1186_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_5_hwPt_V_w_fu_1231_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_6_hwPt_V_w_fu_1276_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_7_hwPt_V_w_fu_1321_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_8_hwPt_V_w_fu_1366_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_9_hwPt_V_w_fu_1411_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_0_hwEta_V_s_fu_1006_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwEta_V_s_fu_1051_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwEta_V_s_fu_1103_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwEta_V_s_fu_1148_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwEta_V_s_fu_1193_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwEta_V_s_fu_1238_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwEta_V_s_fu_1283_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwEta_V_s_fu_1328_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwEta_V_s_fu_1373_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwEta_V_s_fu_1418_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_0_hwPhi_V_s_fu_1021_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwPhi_V_s_fu_1066_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwPhi_V_s_fu_1111_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwPhi_V_s_fu_1156_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwPhi_V_s_fu_1201_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwPhi_V_s_fu_1246_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwPhi_V_s_fu_1291_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwPhi_V_s_fu_1336_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwPhi_V_s_fu_1381_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwPhi_V_s_fu_1426_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                ap_port_reg_calo_0_hwEta_V_read <= calo_0_hwEta_V_read;
                ap_port_reg_calo_0_hwIsEM_read <= calo_0_hwIsEM_read;
                ap_port_reg_calo_0_hwPhi_V_read <= calo_0_hwPhi_V_read;
                ap_port_reg_calo_1_hwEta_V_read <= calo_1_hwEta_V_read;
                ap_port_reg_calo_1_hwIsEM_read <= calo_1_hwIsEM_read;
                ap_port_reg_calo_1_hwPhi_V_read <= calo_1_hwPhi_V_read;
                ap_port_reg_calo_2_hwEta_V_read <= calo_2_hwEta_V_read;
                ap_port_reg_calo_2_hwIsEM_read <= calo_2_hwIsEM_read;
                ap_port_reg_calo_2_hwPhi_V_read <= calo_2_hwPhi_V_read;
                ap_port_reg_calo_3_hwEta_V_read <= calo_3_hwEta_V_read;
                ap_port_reg_calo_3_hwIsEM_read <= calo_3_hwIsEM_read;
                ap_port_reg_calo_3_hwPhi_V_read <= calo_3_hwPhi_V_read;
                ap_port_reg_calo_4_hwEta_V_read <= calo_4_hwEta_V_read;
                ap_port_reg_calo_4_hwIsEM_read <= calo_4_hwIsEM_read;
                ap_port_reg_calo_4_hwPhi_V_read <= calo_4_hwPhi_V_read;
                ap_port_reg_calo_5_hwEta_V_read <= calo_5_hwEta_V_read;
                ap_port_reg_calo_5_hwIsEM_read <= calo_5_hwIsEM_read;
                ap_port_reg_calo_5_hwPhi_V_read <= calo_5_hwPhi_V_read;
                ap_port_reg_calo_6_hwEta_V_read <= calo_6_hwEta_V_read;
                ap_port_reg_calo_6_hwIsEM_read <= calo_6_hwIsEM_read;
                ap_port_reg_calo_6_hwPhi_V_read <= calo_6_hwPhi_V_read;
                ap_port_reg_calo_7_hwEta_V_read <= calo_7_hwEta_V_read;
                ap_port_reg_calo_7_hwIsEM_read <= calo_7_hwIsEM_read;
                ap_port_reg_calo_7_hwPhi_V_read <= calo_7_hwPhi_V_read;
                ap_port_reg_calo_8_hwEta_V_read <= calo_8_hwEta_V_read;
                ap_port_reg_calo_8_hwIsEM_read <= calo_8_hwIsEM_read;
                ap_port_reg_calo_8_hwPhi_V_read <= calo_8_hwPhi_V_read;
                ap_port_reg_calo_9_hwEta_V_read <= calo_9_hwEta_V_read;
                ap_port_reg_calo_9_hwIsEM_read <= calo_9_hwIsEM_read;
                ap_port_reg_calo_9_hwPhi_V_read <= calo_9_hwPhi_V_read;
                emsub_V_2_reg_1662 <= emsub_V_2_fu_574_p2;
                emsub_V_3_reg_1683 <= emsub_V_3_fu_606_p2;
                emsub_V_4_reg_1704 <= emsub_V_4_fu_638_p2;
                emsub_V_5_reg_1725 <= emsub_V_5_fu_670_p2;
                emsub_V_6_reg_1746 <= emsub_V_6_fu_702_p2;
                emsub_V_7_reg_1767 <= emsub_V_7_fu_734_p2;
                emsub_V_8_reg_1788 <= emsub_V_8_fu_766_p2;
                emsub_V_9_reg_1809 <= emsub_V_9_fu_798_p2;
                emsub_V_reg_1620 <= emsub_V_fu_510_p2;
                emsub_V_s_reg_1641 <= emsub_V_s_fu_542_p2;
                ptsub_V_1_reg_1635 <= ptsub_V_1_fu_536_p2;
                ptsub_V_2_reg_1656 <= ptsub_V_2_fu_568_p2;
                ptsub_V_3_reg_1677 <= ptsub_V_3_fu_600_p2;
                ptsub_V_4_reg_1698 <= ptsub_V_4_fu_632_p2;
                ptsub_V_5_reg_1719 <= ptsub_V_5_fu_664_p2;
                ptsub_V_6_reg_1740 <= ptsub_V_6_fu_696_p2;
                ptsub_V_7_reg_1761 <= ptsub_V_7_fu_728_p2;
                ptsub_V_8_reg_1782 <= ptsub_V_8_fu_760_p2;
                ptsub_V_9_reg_1803 <= ptsub_V_9_fu_792_p2;
                ptsub_V_reg_1614 <= ptsub_V_fu_504_p2;
                tmp_100_reg_1693 <= calo_3_hwEmPt_V_rea(15 downto 3);
                tmp_101_reg_1709 <= calo_4_hwPt_V_read(15 downto 4);
                tmp_102_reg_1714 <= calo_4_hwEmPt_V_rea(15 downto 3);
                tmp_103_reg_1730 <= calo_5_hwPt_V_read(15 downto 4);
                tmp_104_reg_1735 <= calo_5_hwEmPt_V_rea(15 downto 3);
                tmp_105_reg_1751 <= calo_6_hwPt_V_read(15 downto 4);
                tmp_106_reg_1756 <= calo_6_hwEmPt_V_rea(15 downto 3);
                tmp_107_reg_1772 <= calo_7_hwPt_V_read(15 downto 4);
                tmp_108_reg_1777 <= calo_7_hwEmPt_V_rea(15 downto 3);
                tmp_109_reg_1793 <= calo_8_hwPt_V_read(15 downto 4);
                tmp_110_reg_1798 <= calo_8_hwEmPt_V_rea(15 downto 3);
                tmp_111_reg_1814 <= calo_9_hwPt_V_read(15 downto 4);
                tmp_112_reg_1819 <= calo_9_hwEmPt_V_rea(15 downto 3);
                tmp_94_reg_1630 <= calo_0_hwEmPt_V_rea(15 downto 3);
                tmp_95_reg_1646 <= calo_1_hwPt_V_read(15 downto 4);
                tmp_96_reg_1651 <= calo_1_hwEmPt_V_rea(15 downto 3);
                tmp_97_reg_1667 <= calo_2_hwPt_V_read(15 downto 4);
                tmp_98_reg_1672 <= calo_2_hwEmPt_V_rea(15 downto 3);
                tmp_99_reg_1688 <= calo_3_hwPt_V_read(15 downto 4);
                tmp_s_reg_1625 <= calo_0_hwPt_V_read(15 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                slt34_reg_1829 <= slt34_fu_835_p2;
                slt35_reg_1834 <= slt35_fu_846_p2;
                slt36_reg_1839 <= slt36_fu_851_p2;
                slt37_reg_1844 <= slt37_fu_862_p2;
                slt38_reg_1849 <= slt38_fu_867_p2;
                slt39_reg_1854 <= slt39_fu_878_p2;
                slt40_reg_1859 <= slt40_fu_883_p2;
                slt41_reg_1864 <= slt41_fu_894_p2;
                slt42_reg_1869 <= slt42_fu_899_p2;
                slt43_reg_1874 <= slt43_fu_910_p2;
                slt44_reg_1879 <= slt44_fu_915_p2;
                slt45_reg_1884 <= slt45_fu_926_p2;
                slt46_reg_1889 <= slt46_fu_931_p2;
                slt47_reg_1894 <= slt47_fu_942_p2;
                slt48_reg_1899 <= slt48_fu_947_p2;
                slt49_reg_1904 <= slt49_fu_958_p2;
                slt50_reg_1909 <= slt50_fu_963_p2;
                slt51_reg_1914 <= slt51_fu_974_p2;
                slt52_reg_1919 <= slt52_fu_979_p2;
                slt_reg_1824 <= slt_fu_830_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= calo_out_0_hwPt_V_w_fu_1014_p3;
    ap_return_1 <= calo_out_1_hwPt_V_w_fu_1059_p3;
    ap_return_10 <= calo_out_0_hwEta_V_s_fu_1006_p3;
    ap_return_11 <= calo_out_1_hwEta_V_s_fu_1051_p3;
    ap_return_12 <= calo_out_2_hwEta_V_s_fu_1103_p3;
    ap_return_13 <= calo_out_3_hwEta_V_s_fu_1148_p3;
    ap_return_14 <= calo_out_4_hwEta_V_s_fu_1193_p3;
    ap_return_15 <= calo_out_5_hwEta_V_s_fu_1238_p3;
    ap_return_16 <= calo_out_6_hwEta_V_s_fu_1283_p3;
    ap_return_17 <= calo_out_7_hwEta_V_s_fu_1328_p3;
    ap_return_18 <= calo_out_8_hwEta_V_s_fu_1373_p3;
    ap_return_19 <= calo_out_9_hwEta_V_s_fu_1418_p3;
    ap_return_2 <= calo_out_2_hwPt_V_w_fu_1096_p3;
    ap_return_20 <= calo_out_0_hwPhi_V_s_fu_1021_p3;
    ap_return_21 <= calo_out_1_hwPhi_V_s_fu_1066_p3;
    ap_return_22 <= calo_out_2_hwPhi_V_s_fu_1111_p3;
    ap_return_23 <= calo_out_3_hwPhi_V_s_fu_1156_p3;
    ap_return_24 <= calo_out_4_hwPhi_V_s_fu_1201_p3;
    ap_return_25 <= calo_out_5_hwPhi_V_s_fu_1246_p3;
    ap_return_26 <= calo_out_6_hwPhi_V_s_fu_1291_p3;
    ap_return_27 <= calo_out_7_hwPhi_V_s_fu_1336_p3;
    ap_return_28 <= calo_out_8_hwPhi_V_s_fu_1381_p3;
    ap_return_29 <= calo_out_9_hwPhi_V_s_fu_1426_p3;
    ap_return_3 <= calo_out_3_hwPt_V_w_fu_1141_p3;
    ap_return_4 <= calo_out_4_hwPt_V_w_fu_1186_p3;
    ap_return_5 <= calo_out_5_hwPt_V_w_fu_1231_p3;
    ap_return_6 <= calo_out_6_hwPt_V_w_fu_1276_p3;
    ap_return_7 <= calo_out_7_hwPt_V_w_fu_1321_p3;
    ap_return_8 <= calo_out_8_hwPt_V_w_fu_1366_p3;
    ap_return_9 <= calo_out_9_hwPt_V_w_fu_1411_p3;
    calo_out_0_hwEta_V_s_fu_1006_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_fu_1000_p2(0) = '1') else 
        ap_port_reg_calo_0_hwEta_V_read;
    calo_out_0_hwPhi_V_s_fu_1021_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_fu_1000_p2(0) = '1') else 
        ap_port_reg_calo_0_hwPhi_V_read;
    calo_out_0_hwPt_V_w_fu_1014_p3 <= 
        ap_const_lv16_0 when (sel_tmp3_fu_1000_p2(0) = '1') else 
        ptsub_V_reg_1614;
    calo_out_1_hwEta_V_s_fu_1051_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_fu_1045_p2(0) = '1') else 
        ap_port_reg_calo_1_hwEta_V_read;
    calo_out_1_hwPhi_V_s_fu_1066_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_fu_1045_p2(0) = '1') else 
        ap_port_reg_calo_1_hwPhi_V_read;
    calo_out_1_hwPt_V_w_fu_1059_p3 <= 
        ap_const_lv16_0 when (sel_tmp18_fu_1045_p2(0) = '1') else 
        ptsub_V_1_reg_1635;
    calo_out_2_hwEta_V_s_fu_1103_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_fu_1090_p2(0) = '1') else 
        ap_port_reg_calo_2_hwEta_V_read;
    calo_out_2_hwPhi_V_s_fu_1111_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_fu_1090_p2(0) = '1') else 
        ap_port_reg_calo_2_hwPhi_V_read;
    calo_out_2_hwPt_V_w_fu_1096_p3 <= 
        ap_const_lv16_0 when (sel_tmp33_fu_1090_p2(0) = '1') else 
        ptsub_V_2_reg_1656;
    calo_out_3_hwEta_V_s_fu_1148_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_fu_1135_p2(0) = '1') else 
        ap_port_reg_calo_3_hwEta_V_read;
    calo_out_3_hwPhi_V_s_fu_1156_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_fu_1135_p2(0) = '1') else 
        ap_port_reg_calo_3_hwPhi_V_read;
    calo_out_3_hwPt_V_w_fu_1141_p3 <= 
        ap_const_lv16_0 when (sel_tmp48_fu_1135_p2(0) = '1') else 
        ptsub_V_3_reg_1677;
    calo_out_4_hwEta_V_s_fu_1193_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_fu_1180_p2(0) = '1') else 
        ap_port_reg_calo_4_hwEta_V_read;
    calo_out_4_hwPhi_V_s_fu_1201_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_fu_1180_p2(0) = '1') else 
        ap_port_reg_calo_4_hwPhi_V_read;
    calo_out_4_hwPt_V_w_fu_1186_p3 <= 
        ap_const_lv16_0 when (sel_tmp63_fu_1180_p2(0) = '1') else 
        ptsub_V_4_reg_1698;
    calo_out_5_hwEta_V_s_fu_1238_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_fu_1225_p2(0) = '1') else 
        ap_port_reg_calo_5_hwEta_V_read;
    calo_out_5_hwPhi_V_s_fu_1246_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_fu_1225_p2(0) = '1') else 
        ap_port_reg_calo_5_hwPhi_V_read;
    calo_out_5_hwPt_V_w_fu_1231_p3 <= 
        ap_const_lv16_0 when (sel_tmp78_fu_1225_p2(0) = '1') else 
        ptsub_V_5_reg_1719;
    calo_out_6_hwEta_V_s_fu_1283_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_fu_1270_p2(0) = '1') else 
        ap_port_reg_calo_6_hwEta_V_read;
    calo_out_6_hwPhi_V_s_fu_1291_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_fu_1270_p2(0) = '1') else 
        ap_port_reg_calo_6_hwPhi_V_read;
    calo_out_6_hwPt_V_w_fu_1276_p3 <= 
        ap_const_lv16_0 when (sel_tmp93_fu_1270_p2(0) = '1') else 
        ptsub_V_6_reg_1740;
    calo_out_7_hwEta_V_s_fu_1328_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_fu_1315_p2(0) = '1') else 
        ap_port_reg_calo_7_hwEta_V_read;
    calo_out_7_hwPhi_V_s_fu_1336_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_fu_1315_p2(0) = '1') else 
        ap_port_reg_calo_7_hwPhi_V_read;
    calo_out_7_hwPt_V_w_fu_1321_p3 <= 
        ap_const_lv16_0 when (sel_tmp108_fu_1315_p2(0) = '1') else 
        ptsub_V_7_reg_1761;
    calo_out_8_hwEta_V_s_fu_1373_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_fu_1360_p2(0) = '1') else 
        ap_port_reg_calo_8_hwEta_V_read;
    calo_out_8_hwPhi_V_s_fu_1381_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_fu_1360_p2(0) = '1') else 
        ap_port_reg_calo_8_hwPhi_V_read;
    calo_out_8_hwPt_V_w_fu_1366_p3 <= 
        ap_const_lv16_0 when (sel_tmp123_fu_1360_p2(0) = '1') else 
        ptsub_V_8_reg_1782;
    calo_out_9_hwEta_V_s_fu_1418_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_fu_1405_p2(0) = '1') else 
        ap_port_reg_calo_9_hwEta_V_read;
    calo_out_9_hwPhi_V_s_fu_1426_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_fu_1405_p2(0) = '1') else 
        ap_port_reg_calo_9_hwPhi_V_read;
    calo_out_9_hwPt_V_w_fu_1411_p3 <= 
        ap_const_lv16_0 when (sel_tmp138_fu_1405_p2(0) = '1') else 
        ptsub_V_9_reg_1803;
    emsub_V_2_fu_574_p2 <= std_logic_vector(unsigned(calo_2_hwEmPt_V_rea) - unsigned(sumem_2_V_read));
    emsub_V_3_fu_606_p2 <= std_logic_vector(unsigned(calo_3_hwEmPt_V_rea) - unsigned(sumem_3_V_read));
    emsub_V_4_fu_638_p2 <= std_logic_vector(unsigned(calo_4_hwEmPt_V_rea) - unsigned(sumem_4_V_read));
    emsub_V_5_fu_670_p2 <= std_logic_vector(unsigned(calo_5_hwEmPt_V_rea) - unsigned(sumem_5_V_read));
    emsub_V_6_fu_702_p2 <= std_logic_vector(unsigned(calo_6_hwEmPt_V_rea) - unsigned(sumem_6_V_read));
    emsub_V_7_fu_734_p2 <= std_logic_vector(unsigned(calo_7_hwEmPt_V_rea) - unsigned(sumem_7_V_read));
    emsub_V_8_fu_766_p2 <= std_logic_vector(unsigned(calo_8_hwEmPt_V_rea) - unsigned(sumem_8_V_read));
    emsub_V_9_fu_798_p2 <= std_logic_vector(unsigned(calo_9_hwEmPt_V_rea) - unsigned(sumem_9_V_read));
    emsub_V_fu_510_p2 <= std_logic_vector(unsigned(calo_0_hwEmPt_V_rea) - unsigned(sumem_0_V_read));
    emsub_V_s_fu_542_p2 <= std_logic_vector(unsigned(calo_1_hwEmPt_V_rea) - unsigned(sumem_1_V_read));
    ptsub_V_1_fu_536_p2 <= std_logic_vector(unsigned(calo_1_hwPt_V_read) - unsigned(sumem_1_V_read));
    ptsub_V_2_fu_568_p2 <= std_logic_vector(unsigned(calo_2_hwPt_V_read) - unsigned(sumem_2_V_read));
    ptsub_V_3_fu_600_p2 <= std_logic_vector(unsigned(calo_3_hwPt_V_read) - unsigned(sumem_3_V_read));
    ptsub_V_4_fu_632_p2 <= std_logic_vector(unsigned(calo_4_hwPt_V_read) - unsigned(sumem_4_V_read));
    ptsub_V_5_fu_664_p2 <= std_logic_vector(unsigned(calo_5_hwPt_V_read) - unsigned(sumem_5_V_read));
    ptsub_V_6_fu_696_p2 <= std_logic_vector(unsigned(calo_6_hwPt_V_read) - unsigned(sumem_6_V_read));
    ptsub_V_7_fu_728_p2 <= std_logic_vector(unsigned(calo_7_hwPt_V_read) - unsigned(sumem_7_V_read));
    ptsub_V_8_fu_760_p2 <= std_logic_vector(unsigned(calo_8_hwPt_V_read) - unsigned(sumem_8_V_read));
    ptsub_V_9_fu_792_p2 <= std_logic_vector(unsigned(calo_9_hwPt_V_read) - unsigned(sumem_9_V_read));
    ptsub_V_fu_504_p2 <= std_logic_vector(unsigned(calo_0_hwPt_V_read) - unsigned(sumem_0_V_read));
        r_V_1_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_95_reg_1646),16));

        r_V_2_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_97_reg_1667),16));

        r_V_3_fu_872_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_99_reg_1688),16));

        r_V_4_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_101_reg_1709),16));

        r_V_5_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_103_reg_1730),16));

        r_V_6_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_105_reg_1751),16));

        r_V_7_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_107_reg_1772),16));

        r_V_8_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_109_reg_1793),16));

        r_V_9_1_fu_843_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_96_reg_1651),16));

        r_V_9_2_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_98_reg_1672),16));

        r_V_9_3_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_100_reg_1693),16));

        r_V_9_4_fu_891_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_102_reg_1714),16));

        r_V_9_5_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_104_reg_1735),16));

        r_V_9_6_fu_923_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_106_reg_1756),16));

        r_V_9_7_fu_939_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_108_reg_1777),16));

        r_V_9_8_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_110_reg_1798),16));

        r_V_9_9_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_112_reg_1819),16));

        r_V_9_fu_827_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_94_reg_1630),16));

        r_V_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_reg_1625),16));

        r_V_s_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_111_reg_1814),16));

    rev34_fu_989_p2 <= (slt34_reg_1829 xor ap_const_lv1_1);
    rev35_fu_1029_p2 <= (slt35_reg_1834 xor ap_const_lv1_1);
    rev36_fu_1034_p2 <= (slt36_reg_1839 xor ap_const_lv1_1);
    rev37_fu_1074_p2 <= (slt37_reg_1844 xor ap_const_lv1_1);
    rev38_fu_1079_p2 <= (slt38_reg_1849 xor ap_const_lv1_1);
    rev39_fu_1119_p2 <= (slt39_reg_1854 xor ap_const_lv1_1);
    rev40_fu_1124_p2 <= (slt40_reg_1859 xor ap_const_lv1_1);
    rev41_fu_1164_p2 <= (slt41_reg_1864 xor ap_const_lv1_1);
    rev42_fu_1169_p2 <= (slt42_reg_1869 xor ap_const_lv1_1);
    rev43_fu_1209_p2 <= (slt43_reg_1874 xor ap_const_lv1_1);
    rev44_fu_1214_p2 <= (slt44_reg_1879 xor ap_const_lv1_1);
    rev45_fu_1254_p2 <= (slt45_reg_1884 xor ap_const_lv1_1);
    rev46_fu_1259_p2 <= (slt46_reg_1889 xor ap_const_lv1_1);
    rev47_fu_1299_p2 <= (slt47_reg_1894 xor ap_const_lv1_1);
    rev48_fu_1304_p2 <= (slt48_reg_1899 xor ap_const_lv1_1);
    rev49_fu_1344_p2 <= (slt49_reg_1904 xor ap_const_lv1_1);
    rev50_fu_1349_p2 <= (slt50_reg_1909 xor ap_const_lv1_1);
    rev51_fu_1389_p2 <= (slt51_reg_1914 xor ap_const_lv1_1);
    rev52_fu_1394_p2 <= (slt52_reg_1919 xor ap_const_lv1_1);
    rev_fu_984_p2 <= (slt_reg_1824 xor ap_const_lv1_1);
    sel_tmp107_fu_1309_p1 <= (0=>ap_port_reg_calo_7_hwIsEM_read, others=>'-');
    sel_tmp107_fu_1309_p2 <= (sel_tmp107_fu_1309_p1 and rev48_fu_1304_p2);
    sel_tmp108_fu_1315_p2 <= (sel_tmp107_fu_1309_p2 or rev47_fu_1299_p2);
    sel_tmp122_fu_1354_p1 <= (0=>ap_port_reg_calo_8_hwIsEM_read, others=>'-');
    sel_tmp122_fu_1354_p2 <= (sel_tmp122_fu_1354_p1 and rev50_fu_1349_p2);
    sel_tmp123_fu_1360_p2 <= (sel_tmp122_fu_1354_p2 or rev49_fu_1344_p2);
    sel_tmp137_fu_1399_p1 <= (0=>ap_port_reg_calo_9_hwIsEM_read, others=>'-');
    sel_tmp137_fu_1399_p2 <= (sel_tmp137_fu_1399_p1 and rev52_fu_1394_p2);
    sel_tmp138_fu_1405_p2 <= (sel_tmp137_fu_1399_p2 or rev51_fu_1389_p2);
    sel_tmp17_fu_1039_p1 <= (0=>ap_port_reg_calo_1_hwIsEM_read, others=>'-');
    sel_tmp17_fu_1039_p2 <= (sel_tmp17_fu_1039_p1 and rev36_fu_1034_p2);
    sel_tmp18_fu_1045_p2 <= (sel_tmp17_fu_1039_p2 or rev35_fu_1029_p2);
    sel_tmp2_fu_994_p1 <= (0=>ap_port_reg_calo_0_hwIsEM_read, others=>'-');
    sel_tmp2_fu_994_p2 <= (sel_tmp2_fu_994_p1 and rev34_fu_989_p2);
    sel_tmp32_fu_1084_p1 <= (0=>ap_port_reg_calo_2_hwIsEM_read, others=>'-');
    sel_tmp32_fu_1084_p2 <= (sel_tmp32_fu_1084_p1 and rev38_fu_1079_p2);
    sel_tmp33_fu_1090_p2 <= (sel_tmp32_fu_1084_p2 or rev37_fu_1074_p2);
    sel_tmp3_fu_1000_p2 <= (sel_tmp2_fu_994_p2 or rev_fu_984_p2);
    sel_tmp47_fu_1129_p1 <= (0=>ap_port_reg_calo_3_hwIsEM_read, others=>'-');
    sel_tmp47_fu_1129_p2 <= (sel_tmp47_fu_1129_p1 and rev40_fu_1124_p2);
    sel_tmp48_fu_1135_p2 <= (sel_tmp47_fu_1129_p2 or rev39_fu_1119_p2);
    sel_tmp62_fu_1174_p1 <= (0=>ap_port_reg_calo_4_hwIsEM_read, others=>'-');
    sel_tmp62_fu_1174_p2 <= (sel_tmp62_fu_1174_p1 and rev42_fu_1169_p2);
    sel_tmp63_fu_1180_p2 <= (sel_tmp62_fu_1174_p2 or rev41_fu_1164_p2);
    sel_tmp77_fu_1219_p1 <= (0=>ap_port_reg_calo_5_hwIsEM_read, others=>'-');
    sel_tmp77_fu_1219_p2 <= (sel_tmp77_fu_1219_p1 and rev44_fu_1214_p2);
    sel_tmp78_fu_1225_p2 <= (sel_tmp77_fu_1219_p2 or rev43_fu_1209_p2);
    sel_tmp92_fu_1264_p1 <= (0=>ap_port_reg_calo_6_hwIsEM_read, others=>'-');
    sel_tmp92_fu_1264_p2 <= (sel_tmp92_fu_1264_p1 and rev46_fu_1259_p2);
    sel_tmp93_fu_1270_p2 <= (sel_tmp92_fu_1264_p2 or rev45_fu_1254_p2);
    slt34_fu_835_p2 <= "1" when (signed(r_V_9_fu_827_p1) < signed(emsub_V_reg_1620)) else "0";
    slt35_fu_846_p2 <= "1" when (signed(r_V_1_fu_840_p1) < signed(ptsub_V_1_reg_1635)) else "0";
    slt36_fu_851_p2 <= "1" when (signed(r_V_9_1_fu_843_p1) < signed(emsub_V_s_reg_1641)) else "0";
    slt37_fu_862_p2 <= "1" when (signed(r_V_2_fu_856_p1) < signed(ptsub_V_2_reg_1656)) else "0";
    slt38_fu_867_p2 <= "1" when (signed(r_V_9_2_fu_859_p1) < signed(emsub_V_2_reg_1662)) else "0";
    slt39_fu_878_p2 <= "1" when (signed(r_V_3_fu_872_p1) < signed(ptsub_V_3_reg_1677)) else "0";
    slt40_fu_883_p2 <= "1" when (signed(r_V_9_3_fu_875_p1) < signed(emsub_V_3_reg_1683)) else "0";
    slt41_fu_894_p2 <= "1" when (signed(r_V_4_fu_888_p1) < signed(ptsub_V_4_reg_1698)) else "0";
    slt42_fu_899_p2 <= "1" when (signed(r_V_9_4_fu_891_p1) < signed(emsub_V_4_reg_1704)) else "0";
    slt43_fu_910_p2 <= "1" when (signed(r_V_5_fu_904_p1) < signed(ptsub_V_5_reg_1719)) else "0";
    slt44_fu_915_p2 <= "1" when (signed(r_V_9_5_fu_907_p1) < signed(emsub_V_5_reg_1725)) else "0";
    slt45_fu_926_p2 <= "1" when (signed(r_V_6_fu_920_p1) < signed(ptsub_V_6_reg_1740)) else "0";
    slt46_fu_931_p2 <= "1" when (signed(r_V_9_6_fu_923_p1) < signed(emsub_V_6_reg_1746)) else "0";
    slt47_fu_942_p2 <= "1" when (signed(r_V_7_fu_936_p1) < signed(ptsub_V_7_reg_1761)) else "0";
    slt48_fu_947_p2 <= "1" when (signed(r_V_9_7_fu_939_p1) < signed(emsub_V_7_reg_1767)) else "0";
    slt49_fu_958_p2 <= "1" when (signed(r_V_8_fu_952_p1) < signed(ptsub_V_8_reg_1782)) else "0";
    slt50_fu_963_p2 <= "1" when (signed(r_V_9_8_fu_955_p1) < signed(emsub_V_8_reg_1788)) else "0";
    slt51_fu_974_p2 <= "1" when (signed(r_V_s_fu_968_p1) < signed(ptsub_V_9_reg_1803)) else "0";
    slt52_fu_979_p2 <= "1" when (signed(r_V_9_9_fu_971_p1) < signed(emsub_V_9_reg_1809)) else "0";
    slt_fu_830_p2 <= "1" when (signed(r_V_fu_824_p1) < signed(ptsub_V_reg_1614)) else "0";
end behav;
