-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity abs_11_s is
port (
    ap_ready : OUT STD_LOGIC;
    x_V : IN STD_LOGIC_VECTOR (10 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (10 downto 0) );
end;


architecture behav of abs_11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal xs_V_1_fu_20_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Result_s_fu_36_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_26_p4 : STD_LOGIC_VECTOR (10 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        p_Result_1_fu_26_p4 when (p_Result_s_fu_36_p3(0) = '1') else 
        x_V;
    
    p_Result_1_fu_26_p4_proc : process(xs_V_1_fu_20_p2)
    begin
        p_Result_1_fu_26_p4 <= xs_V_1_fu_20_p2;
        p_Result_1_fu_26_p4(10) <= ap_const_lv1_0(0);
    end process;

    p_Result_s_fu_36_p3 <= x_V(10 downto 10);
    xs_V_1_fu_20_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(x_V));
end behav;
