-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dr2_int_cap_14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    eta1_V : IN STD_LOGIC_VECTOR (9 downto 0);
    phi1_V : IN STD_LOGIC_VECTOR (9 downto 0);
    eta2_V : IN STD_LOGIC_VECTOR (9 downto 0);
    phi2_V : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of dr2_int_cap_14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv15_20D5 : STD_LOGIC_VECTOR (14 downto 0) := "010000011010101";
    constant ap_const_lv14_20D5 : STD_LOGIC_VECTOR (13 downto 0) := "10000011010101";

    signal r_V_fu_56_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_reg_179 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal r_V_reg_179_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_1_fu_70_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_1_reg_186 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_1_reg_186_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_76_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_193 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_81_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_s_reg_198 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_203 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_91_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_reg_208 : STD_LOGIC_VECTOR (10 downto 0);
    signal deta_V_fu_96_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal deta_V_reg_213 : STD_LOGIC_VECTOR (10 downto 0);
    signal dphi_V_fu_101_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal dphi_V_reg_218 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_fu_122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_223 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_223_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_223_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal deta2_V_fu_167_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal deta2_V_reg_228 : STD_LOGIC_VECTOR (13 downto 0);
    signal dphi2_V_fu_173_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal dphi2_V_reg_233 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_2_fu_140_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_2_reg_238 : STD_LOGIC_VECTOR (14 downto 0);
    signal val_assign_fu_146_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal val_assign_reg_243 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_768_fu_152_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_768_reg_248 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_768_reg_248_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_9_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_253 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal lhs_V_fu_48_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal rhs_V_fu_52_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_V_1_fu_62_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal rhs_V_1_fu_66_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_106_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_767_fu_112_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal rhs_V_2_fu_137_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal lhs_V_2_fu_134_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal deta2_V_fu_167_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal deta_V_cast2_fu_128_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal deta2_V_fu_167_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal dphi2_V_fu_173_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal dphi_V_cast1_fu_131_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal dphi2_V_fu_173_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal agg_result_V_fu_161_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal eta1_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal phi1_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal eta2_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal phi2_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (13 downto 0);

    component mp7wrapped_pfalgoeOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    mp7wrapped_pfalgoeOg_U205 : component mp7wrapped_pfalgoeOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 11,
        dout_WIDTH => 14)
    port map (
        din0 => deta2_V_fu_167_p0,
        din1 => deta2_V_fu_167_p1,
        dout => deta2_V_fu_167_p2);

    mp7wrapped_pfalgoeOg_U206 : component mp7wrapped_pfalgoeOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 11,
        dout_WIDTH => 14)
    port map (
        din0 => dphi2_V_fu_173_p0,
        din1 => dphi2_V_fu_173_p1,
        dout => dphi2_V_fu_173_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= agg_result_V_fu_161_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_reg_223 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                deta2_V_reg_228 <= deta2_V_fu_167_p2;
                dphi2_V_reg_233 <= dphi2_V_fu_173_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                deta_V_reg_213 <= deta_V_fu_96_p3;
                dphi_V_reg_218 <= dphi_V_fu_101_p3;
                icmp_reg_223 <= icmp_fu_122_p2;
                icmp_reg_223_pp0_iter3_reg <= icmp_reg_223;
                icmp_reg_223_pp0_iter4_reg <= icmp_reg_223_pp0_iter3_reg;
                r_V_1_reg_186 <= r_V_1_fu_70_p2;
                r_V_1_reg_186_pp0_iter1_reg <= r_V_1_reg_186;
                r_V_reg_179 <= r_V_fu_56_p2;
                r_V_reg_179_pp0_iter1_reg <= r_V_reg_179;
                tmp_5_reg_203 <= tmp_5_fu_86_p2;
                tmp_6_reg_208 <= tmp_6_fu_91_p2;
                tmp_768_reg_248 <= tmp_768_fu_152_p1;
                tmp_768_reg_248_pp0_iter6_reg <= tmp_768_reg_248;
                tmp_9_reg_253 <= tmp_9_fu_156_p2;
                tmp_reg_193 <= tmp_fu_76_p2;
                tmp_s_reg_198 <= tmp_s_fu_81_p2;
                val_assign_reg_243 <= val_assign_fu_146_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                eta1_V_int_reg <= eta1_V;
                eta2_V_int_reg <= eta2_V;
                phi1_V_int_reg <= phi1_V;
                phi2_V_int_reg <= phi2_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_reg_223_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                r_V_2_reg_238 <= r_V_2_fu_140_p2;
            end if;
        end if;
    end process;
    agg_result_V_fu_161_p3 <= 
        tmp_768_reg_248_pp0_iter6_reg when (tmp_9_reg_253(0) = '1') else 
        ap_const_lv14_20D5;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(agg_result_V_fu_161_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= agg_result_V_fu_161_p3;
        end if; 
    end process;

    deta2_V_fu_167_p0 <= deta_V_cast2_fu_128_p1(11 - 1 downto 0);
    deta2_V_fu_167_p1 <= deta_V_cast2_fu_128_p1(11 - 1 downto 0);
        deta_V_cast2_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(deta_V_reg_213),14));

    deta_V_fu_96_p3 <= 
        r_V_reg_179_pp0_iter1_reg when (tmp_reg_193(0) = '1') else 
        tmp_s_reg_198;
    dphi2_V_fu_173_p0 <= dphi_V_cast1_fu_131_p1(11 - 1 downto 0);
    dphi2_V_fu_173_p1 <= dphi_V_cast1_fu_131_p1(11 - 1 downto 0);
        dphi_V_cast1_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(dphi_V_reg_218),14));

    dphi_V_fu_101_p3 <= 
        r_V_1_reg_186_pp0_iter1_reg when (tmp_5_reg_203(0) = '1') else 
        tmp_6_reg_208;
    icmp_fu_122_p2 <= "1" when (tmp_767_fu_112_p4 = ap_const_lv4_0) else "0";
        lhs_V_1_fu_62_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(phi1_V_int_reg),11));

    lhs_V_2_fu_134_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(deta2_V_reg_228),15));
        lhs_V_fu_48_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(eta1_V_int_reg),11));

    r_V_1_fu_70_p2 <= std_logic_vector(signed(lhs_V_1_fu_62_p1) - signed(rhs_V_1_fu_66_p1));
    r_V_2_fu_140_p2 <= std_logic_vector(unsigned(rhs_V_2_fu_137_p1) + unsigned(lhs_V_2_fu_134_p1));
    r_V_fu_56_p2 <= std_logic_vector(signed(lhs_V_fu_48_p1) - signed(rhs_V_fu_52_p1));
        rhs_V_1_fu_66_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(phi2_V_int_reg),11));

    rhs_V_2_fu_137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dphi2_V_reg_233),15));
        rhs_V_fu_52_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(eta2_V_int_reg),11));

    tmp_5_fu_86_p2 <= "1" when (signed(r_V_1_reg_186) > signed(ap_const_lv11_0)) else "0";
    tmp_6_fu_91_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(r_V_1_reg_186));
    tmp_767_fu_112_p4 <= tmp_7_fu_106_p2(10 downto 7);
    tmp_768_fu_152_p1 <= val_assign_fu_146_p3(14 - 1 downto 0);
    tmp_7_fu_106_p2 <= (dphi_V_fu_101_p3 or deta_V_fu_96_p3);
    tmp_9_fu_156_p2 <= "1" when (unsigned(val_assign_reg_243) < unsigned(ap_const_lv15_20D5)) else "0";
    tmp_fu_76_p2 <= "1" when (signed(r_V_reg_179) > signed(ap_const_lv11_0)) else "0";
    tmp_s_fu_81_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(r_V_reg_179));
    val_assign_fu_146_p3 <= 
        r_V_2_reg_238 when (icmp_reg_223_pp0_iter4_reg(0) = '1') else 
        ap_const_lv15_20D5;
end behav;
