-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dr2_int_cap_10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    eta1_V : IN STD_LOGIC_VECTOR (9 downto 0);
    phi1_V : IN STD_LOGIC_VECTOR (9 downto 0);
    eta2_V : IN STD_LOGIC_VECTOR (9 downto 0);
    phi2_V : IN STD_LOGIC_VECTOR (9 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of dr2_int_cap_10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv11_20D : STD_LOGIC_VECTOR (10 downto 0) := "01000001101";
    constant ap_const_lv10_20D : STD_LOGIC_VECTOR (9 downto 0) := "1000001101";

    signal r_V_fu_58_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_reg_180 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_771_fu_64_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_771_reg_185 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_771_reg_185_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_5_fu_76_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_5_reg_191 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_772_fu_82_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_772_reg_196 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_772_reg_196_pp0_iter1_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_202 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_91_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_reg_207 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_17_fu_96_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_212 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_101_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_18_reg_217 : STD_LOGIC_VECTOR (9 downto 0);
    signal deta_V_fu_106_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal deta_V_reg_222 : STD_LOGIC_VECTOR (9 downto 0);
    signal dphi_V_fu_111_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal dphi_V_reg_228 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_234 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_234_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal deta2_V_fu_172_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal deta2_V_reg_239 : STD_LOGIC_VECTOR (9 downto 0);
    signal dphi2_V_fu_176_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal dphi2_V_reg_244 : STD_LOGIC_VECTOR (9 downto 0);
    signal val_assign_fu_150_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal val_assign_reg_249 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_774_fu_157_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_774_reg_254 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_774_reg_254_pp0_iter5_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_21_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_reg_259 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal lhs_V_fu_50_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal rhs_V_fu_54_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_V_5_fu_68_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal rhs_V_5_fu_72_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_19_fu_116_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_773_fu_122_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal rhs_V_6_fu_141_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_V_6_fu_138_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_6_fu_144_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal agg_result_V_fu_166_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal eta1_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal phi1_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal eta2_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal phi2_V_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (9 downto 0);

    component mp7wrapped_pfalgog8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    mp7wrapped_pfalgog8j_U579 : component mp7wrapped_pfalgog8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        din0 => deta_V_reg_222,
        din1 => deta_V_reg_222,
        dout => deta2_V_fu_172_p2);

    mp7wrapped_pfalgog8j_U580 : component mp7wrapped_pfalgog8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        din0 => dphi_V_reg_228,
        din1 => dphi_V_reg_228,
        dout => dphi2_V_fu_176_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= agg_result_V_fu_166_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_reg_234 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                deta2_V_reg_239 <= deta2_V_fu_172_p2;
                dphi2_V_reg_244 <= dphi2_V_fu_176_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                deta_V_reg_222 <= deta_V_fu_106_p3;
                dphi_V_reg_228 <= dphi_V_fu_111_p3;
                icmp_reg_234 <= icmp_fu_132_p2;
                icmp_reg_234_pp0_iter3_reg <= icmp_reg_234;
                r_V_5_reg_191 <= r_V_5_fu_76_p2;
                r_V_reg_180 <= r_V_fu_58_p2;
                tmp_17_reg_212 <= tmp_17_fu_96_p2;
                tmp_18_reg_217 <= tmp_18_fu_101_p2;
                tmp_21_reg_259 <= tmp_21_fu_161_p2;
                tmp_771_reg_185 <= tmp_771_fu_64_p1;
                tmp_771_reg_185_pp0_iter1_reg <= tmp_771_reg_185;
                tmp_772_reg_196 <= tmp_772_fu_82_p1;
                tmp_772_reg_196_pp0_iter1_reg <= tmp_772_reg_196;
                tmp_774_reg_254 <= tmp_774_fu_157_p1;
                tmp_774_reg_254_pp0_iter5_reg <= tmp_774_reg_254;
                tmp_reg_202 <= tmp_fu_86_p2;
                tmp_s_reg_207 <= tmp_s_fu_91_p2;
                val_assign_reg_249 <= val_assign_fu_150_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                eta1_V_int_reg <= eta1_V;
                eta2_V_int_reg <= eta2_V;
                phi1_V_int_reg <= phi1_V;
                phi2_V_int_reg <= phi2_V;
            end if;
        end if;
    end process;
    agg_result_V_fu_166_p3 <= 
        tmp_774_reg_254_pp0_iter5_reg when (tmp_21_reg_259(0) = '1') else 
        ap_const_lv10_20D;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(agg_result_V_fu_166_p3, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= agg_result_V_fu_166_p3;
        end if; 
    end process;

    deta_V_fu_106_p3 <= 
        tmp_771_reg_185_pp0_iter1_reg when (tmp_reg_202(0) = '1') else 
        tmp_s_reg_207;
    dphi_V_fu_111_p3 <= 
        tmp_772_reg_196_pp0_iter1_reg when (tmp_17_reg_212(0) = '1') else 
        tmp_18_reg_217;
    icmp_fu_132_p2 <= "1" when (tmp_773_fu_122_p4 = ap_const_lv5_0) else "0";
        lhs_V_5_fu_68_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(phi1_V_int_reg),11));

    lhs_V_6_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(deta2_V_reg_239),11));
        lhs_V_fu_50_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(eta1_V_int_reg),11));

    r_V_5_fu_76_p2 <= std_logic_vector(signed(lhs_V_5_fu_68_p1) - signed(rhs_V_5_fu_72_p1));
    r_V_6_fu_144_p2 <= std_logic_vector(unsigned(rhs_V_6_fu_141_p1) + unsigned(lhs_V_6_fu_138_p1));
    r_V_fu_58_p2 <= std_logic_vector(signed(lhs_V_fu_50_p1) - signed(rhs_V_fu_54_p1));
        rhs_V_5_fu_72_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(phi2_V_int_reg),11));

    rhs_V_6_fu_141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dphi2_V_reg_244),11));
        rhs_V_fu_54_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(eta2_V_int_reg),11));

    tmp_17_fu_96_p2 <= "1" when (signed(r_V_5_reg_191) > signed(ap_const_lv11_0)) else "0";
    tmp_18_fu_101_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(tmp_772_reg_196));
    tmp_19_fu_116_p2 <= (dphi_V_fu_111_p3 or deta_V_fu_106_p3);
    tmp_21_fu_161_p2 <= "1" when (unsigned(val_assign_reg_249) < unsigned(ap_const_lv11_20D)) else "0";
    tmp_771_fu_64_p1 <= r_V_fu_58_p2(10 - 1 downto 0);
    tmp_772_fu_82_p1 <= r_V_5_fu_76_p2(10 - 1 downto 0);
    tmp_773_fu_122_p4 <= tmp_19_fu_116_p2(9 downto 5);
    tmp_774_fu_157_p1 <= val_assign_fu_150_p3(10 - 1 downto 0);
    tmp_fu_86_p2 <= "1" when (signed(r_V_reg_180) > signed(ap_const_lv11_0)) else "0";
    tmp_s_fu_91_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(tmp_771_reg_185));
    val_assign_fu_150_p3 <= 
        r_V_6_fu_144_p2 when (icmp_reg_234_pp0_iter3_reg(0) = '1') else 
        ap_const_lv11_20D;
end behav;
