-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity em2calo_sub is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    calo_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwEta_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_5_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_6_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_7_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_8_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_9_hwPhi_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    calo_0_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_1_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_2_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_3_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_4_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_5_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_6_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_7_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_8_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_9_hwEmPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_0_hwIsEM_read : IN STD_LOGIC;
    calo_1_hwIsEM_read : IN STD_LOGIC;
    calo_2_hwIsEM_read : IN STD_LOGIC;
    calo_3_hwIsEM_read : IN STD_LOGIC;
    calo_4_hwIsEM_read : IN STD_LOGIC;
    calo_5_hwIsEM_read : IN STD_LOGIC;
    calo_6_hwIsEM_read : IN STD_LOGIC;
    calo_7_hwIsEM_read : IN STD_LOGIC;
    calo_8_hwIsEM_read : IN STD_LOGIC;
    calo_9_hwIsEM_read : IN STD_LOGIC;
    sumem_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    sumem_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of em2calo_sub is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ptsub_V_fu_504_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_reg_1584 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal emsub_V_fu_510_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_reg_1590 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_reg_1595 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_58_reg_1600 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_1_fu_536_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_1_reg_1605 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_s_fu_542_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_s_reg_1611 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_59_reg_1616 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_60_reg_1621 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_2_fu_568_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_2_reg_1626 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_2_fu_574_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_2_reg_1632 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_61_reg_1637 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_62_reg_1642 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_3_fu_600_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_3_reg_1647 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_3_fu_606_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_3_reg_1653 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_63_reg_1658 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_64_reg_1663 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_4_fu_632_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_4_reg_1668 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_4_fu_638_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_4_reg_1674 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_65_reg_1679 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_66_reg_1684 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_5_fu_664_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_5_reg_1689 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_5_fu_670_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_5_reg_1695 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_67_reg_1700 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_68_reg_1705 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_6_fu_696_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_6_reg_1710 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_6_fu_702_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_6_reg_1716 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_69_reg_1721 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_70_reg_1726 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_7_fu_728_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_7_reg_1731 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_7_fu_734_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_7_reg_1737 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_71_reg_1742 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_72_reg_1747 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_8_fu_760_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_8_reg_1752 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_8_fu_766_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_8_reg_1758 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_73_reg_1763 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_74_reg_1768 : STD_LOGIC_VECTOR (12 downto 0);
    signal ptsub_V_9_fu_792_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ptsub_V_9_reg_1773 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_9_fu_798_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal emsub_V_9_reg_1779 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_75_reg_1784 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_76_reg_1789 : STD_LOGIC_VECTOR (12 downto 0);
    signal calo_9_hwIsEM_read_1_reg_1794 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_8_hwIsEM_read_1_reg_1799 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_7_hwIsEM_read_1_reg_1804 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_6_hwIsEM_read_1_reg_1809 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_5_hwIsEM_read_1_reg_1814 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_4_hwIsEM_read_1_reg_1819 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_3_hwIsEM_read_1_reg_1824 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_2_hwIsEM_read_1_reg_1829 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_1_hwIsEM_read_1_reg_1834 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_0_hwIsEM_read_1_reg_1839 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_9_hwPhi_V_read_7_reg_1844 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_8_hwPhi_V_read_7_reg_1849 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_7_hwPhi_V_read_7_reg_1854 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_6_hwPhi_V_read_7_reg_1859 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_5_hwPhi_V_read_7_reg_1864 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_4_hwPhi_V_read_7_reg_1869 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_3_hwPhi_V_read_7_reg_1874 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_2_hwPhi_V_read_7_reg_1879 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_1_hwPhi_V_read_7_reg_1884 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_0_hwPhi_V_read_7_reg_1889 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_9_hwEta_V_read_7_reg_1894 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_8_hwEta_V_read_7_reg_1899 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_7_hwEta_V_read_7_reg_1904 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_6_hwEta_V_read_7_reg_1909 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_5_hwEta_V_read_7_reg_1914 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_4_hwEta_V_read_7_reg_1919 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_3_hwEta_V_read_7_reg_1924 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_2_hwEta_V_read_7_reg_1929 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_1_hwEta_V_read_7_reg_1934 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_0_hwEta_V_read_7_reg_1939 : STD_LOGIC_VECTOR (9 downto 0);
    signal slt_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt_reg_1944 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt34_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt34_reg_1949 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt35_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt35_reg_1954 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt36_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt36_reg_1959 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt37_fu_862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt37_reg_1964 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt38_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt38_reg_1969 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt39_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt39_reg_1974 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt40_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt40_reg_1979 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt41_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt41_reg_1984 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt42_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt42_reg_1989 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt43_fu_910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt43_reg_1994 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt44_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt44_reg_1999 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt45_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt45_reg_2004 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt46_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt46_reg_2009 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt47_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt47_reg_2014 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt48_fu_947_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt48_reg_2019 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt49_fu_958_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt49_reg_2024 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt50_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt50_reg_2029 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt51_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt51_reg_2034 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt52_fu_979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal slt52_reg_2039 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_port_reg_calo_0_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwEta_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_0_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_1_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_2_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_3_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_4_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_5_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_6_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_7_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_8_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_9_hwPhi_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_calo_0_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_1_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_2_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_3_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_4_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_5_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_6_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_7_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_8_hwIsEM_read : STD_LOGIC;
    signal ap_port_reg_calo_9_hwIsEM_read : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal r_V_fu_824_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_fu_827_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_1_fu_840_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_1_fu_843_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_2_fu_856_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_2_fu_859_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_3_fu_872_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_3_fu_875_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_4_fu_888_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_4_fu_891_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_5_fu_904_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_5_fu_907_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_6_fu_920_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_6_fu_923_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_7_fu_936_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_7_fu_939_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_8_fu_952_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_8_fu_955_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_s_fu_968_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_9_9_fu_971_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal rev34_fu_989_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_999_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev36_fu_1031_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev35_fu_1026_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_1041_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev38_fu_1073_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp32_fu_1078_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev37_fu_1068_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev40_fu_1115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev39_fu_1110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_1125_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev42_fu_1157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev41_fu_1152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp63_fu_1167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev44_fu_1199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp77_fu_1204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev43_fu_1194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp78_fu_1209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev46_fu_1241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp92_fu_1246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev45_fu_1236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp93_fu_1251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev48_fu_1283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp107_fu_1288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev47_fu_1278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp108_fu_1293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev50_fu_1325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp122_fu_1330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev49_fu_1320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp123_fu_1335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev52_fu_1367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp137_fu_1372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev51_fu_1362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp138_fu_1377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal calo_out_0_hwPt_V_w_fu_1012_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_1_hwPt_V_w_fu_1054_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_2_hwPt_V_w_fu_1089_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_3_hwPt_V_w_fu_1131_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_4_hwPt_V_w_fu_1173_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_5_hwPt_V_w_fu_1215_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_6_hwPt_V_w_fu_1257_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_7_hwPt_V_w_fu_1299_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_8_hwPt_V_w_fu_1341_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_9_hwPt_V_w_fu_1383_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal calo_out_0_hwEta_V_s_fu_1005_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwEta_V_s_fu_1047_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwEta_V_s_fu_1096_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwEta_V_s_fu_1138_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwEta_V_s_fu_1180_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwEta_V_s_fu_1222_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwEta_V_s_fu_1264_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwEta_V_s_fu_1306_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwEta_V_s_fu_1348_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwEta_V_s_fu_1390_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_0_hwPhi_V_s_fu_1019_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_1_hwPhi_V_s_fu_1061_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_2_hwPhi_V_s_fu_1103_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_3_hwPhi_V_s_fu_1145_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_4_hwPhi_V_s_fu_1187_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_5_hwPhi_V_s_fu_1229_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_6_hwPhi_V_s_fu_1271_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_7_hwPhi_V_s_fu_1313_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_8_hwPhi_V_s_fu_1355_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal calo_out_9_hwPhi_V_s_fu_1397_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_port_reg_calo_0_hwEta_V_read <= calo_0_hwEta_V_read;
                ap_port_reg_calo_0_hwIsEM_read <= calo_0_hwIsEM_read;
                ap_port_reg_calo_0_hwPhi_V_read <= calo_0_hwPhi_V_read;
                ap_port_reg_calo_1_hwEta_V_read <= calo_1_hwEta_V_read;
                ap_port_reg_calo_1_hwIsEM_read <= calo_1_hwIsEM_read;
                ap_port_reg_calo_1_hwPhi_V_read <= calo_1_hwPhi_V_read;
                ap_port_reg_calo_2_hwEta_V_read <= calo_2_hwEta_V_read;
                ap_port_reg_calo_2_hwIsEM_read <= calo_2_hwIsEM_read;
                ap_port_reg_calo_2_hwPhi_V_read <= calo_2_hwPhi_V_read;
                ap_port_reg_calo_3_hwEta_V_read <= calo_3_hwEta_V_read;
                ap_port_reg_calo_3_hwIsEM_read <= calo_3_hwIsEM_read;
                ap_port_reg_calo_3_hwPhi_V_read <= calo_3_hwPhi_V_read;
                ap_port_reg_calo_4_hwEta_V_read <= calo_4_hwEta_V_read;
                ap_port_reg_calo_4_hwIsEM_read <= calo_4_hwIsEM_read;
                ap_port_reg_calo_4_hwPhi_V_read <= calo_4_hwPhi_V_read;
                ap_port_reg_calo_5_hwEta_V_read <= calo_5_hwEta_V_read;
                ap_port_reg_calo_5_hwIsEM_read <= calo_5_hwIsEM_read;
                ap_port_reg_calo_5_hwPhi_V_read <= calo_5_hwPhi_V_read;
                ap_port_reg_calo_6_hwEta_V_read <= calo_6_hwEta_V_read;
                ap_port_reg_calo_6_hwIsEM_read <= calo_6_hwIsEM_read;
                ap_port_reg_calo_6_hwPhi_V_read <= calo_6_hwPhi_V_read;
                ap_port_reg_calo_7_hwEta_V_read <= calo_7_hwEta_V_read;
                ap_port_reg_calo_7_hwIsEM_read <= calo_7_hwIsEM_read;
                ap_port_reg_calo_7_hwPhi_V_read <= calo_7_hwPhi_V_read;
                ap_port_reg_calo_8_hwEta_V_read <= calo_8_hwEta_V_read;
                ap_port_reg_calo_8_hwIsEM_read <= calo_8_hwIsEM_read;
                ap_port_reg_calo_8_hwPhi_V_read <= calo_8_hwPhi_V_read;
                ap_port_reg_calo_9_hwEta_V_read <= calo_9_hwEta_V_read;
                ap_port_reg_calo_9_hwIsEM_read <= calo_9_hwIsEM_read;
                ap_port_reg_calo_9_hwPhi_V_read <= calo_9_hwPhi_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                calo_0_hwEta_V_read_7_reg_1939 <= ap_port_reg_calo_0_hwEta_V_read;
                calo_0_hwIsEM_read_1_reg_1839 <= (0=>ap_port_reg_calo_0_hwIsEM_read, others=>'-');
                calo_0_hwPhi_V_read_7_reg_1889 <= ap_port_reg_calo_0_hwPhi_V_read;
                calo_1_hwEta_V_read_7_reg_1934 <= ap_port_reg_calo_1_hwEta_V_read;
                calo_1_hwIsEM_read_1_reg_1834 <= (0=>ap_port_reg_calo_1_hwIsEM_read, others=>'-');
                calo_1_hwPhi_V_read_7_reg_1884 <= ap_port_reg_calo_1_hwPhi_V_read;
                calo_2_hwEta_V_read_7_reg_1929 <= ap_port_reg_calo_2_hwEta_V_read;
                calo_2_hwIsEM_read_1_reg_1829 <= (0=>ap_port_reg_calo_2_hwIsEM_read, others=>'-');
                calo_2_hwPhi_V_read_7_reg_1879 <= ap_port_reg_calo_2_hwPhi_V_read;
                calo_3_hwEta_V_read_7_reg_1924 <= ap_port_reg_calo_3_hwEta_V_read;
                calo_3_hwIsEM_read_1_reg_1824 <= (0=>ap_port_reg_calo_3_hwIsEM_read, others=>'-');
                calo_3_hwPhi_V_read_7_reg_1874 <= ap_port_reg_calo_3_hwPhi_V_read;
                calo_4_hwEta_V_read_7_reg_1919 <= ap_port_reg_calo_4_hwEta_V_read;
                calo_4_hwIsEM_read_1_reg_1819 <= (0=>ap_port_reg_calo_4_hwIsEM_read, others=>'-');
                calo_4_hwPhi_V_read_7_reg_1869 <= ap_port_reg_calo_4_hwPhi_V_read;
                calo_5_hwEta_V_read_7_reg_1914 <= ap_port_reg_calo_5_hwEta_V_read;
                calo_5_hwIsEM_read_1_reg_1814 <= (0=>ap_port_reg_calo_5_hwIsEM_read, others=>'-');
                calo_5_hwPhi_V_read_7_reg_1864 <= ap_port_reg_calo_5_hwPhi_V_read;
                calo_6_hwEta_V_read_7_reg_1909 <= ap_port_reg_calo_6_hwEta_V_read;
                calo_6_hwIsEM_read_1_reg_1809 <= (0=>ap_port_reg_calo_6_hwIsEM_read, others=>'-');
                calo_6_hwPhi_V_read_7_reg_1859 <= ap_port_reg_calo_6_hwPhi_V_read;
                calo_7_hwEta_V_read_7_reg_1904 <= ap_port_reg_calo_7_hwEta_V_read;
                calo_7_hwIsEM_read_1_reg_1804 <= (0=>ap_port_reg_calo_7_hwIsEM_read, others=>'-');
                calo_7_hwPhi_V_read_7_reg_1854 <= ap_port_reg_calo_7_hwPhi_V_read;
                calo_8_hwEta_V_read_7_reg_1899 <= ap_port_reg_calo_8_hwEta_V_read;
                calo_8_hwIsEM_read_1_reg_1799 <= (0=>ap_port_reg_calo_8_hwIsEM_read, others=>'-');
                calo_8_hwPhi_V_read_7_reg_1849 <= ap_port_reg_calo_8_hwPhi_V_read;
                calo_9_hwEta_V_read_7_reg_1894 <= ap_port_reg_calo_9_hwEta_V_read;
                calo_9_hwIsEM_read_1_reg_1794 <= (0=>ap_port_reg_calo_9_hwIsEM_read, others=>'-');
                calo_9_hwPhi_V_read_7_reg_1844 <= ap_port_reg_calo_9_hwPhi_V_read;
                slt34_reg_1949 <= slt34_fu_835_p2;
                slt35_reg_1954 <= slt35_fu_846_p2;
                slt36_reg_1959 <= slt36_fu_851_p2;
                slt37_reg_1964 <= slt37_fu_862_p2;
                slt38_reg_1969 <= slt38_fu_867_p2;
                slt39_reg_1974 <= slt39_fu_878_p2;
                slt40_reg_1979 <= slt40_fu_883_p2;
                slt41_reg_1984 <= slt41_fu_894_p2;
                slt42_reg_1989 <= slt42_fu_899_p2;
                slt43_reg_1994 <= slt43_fu_910_p2;
                slt44_reg_1999 <= slt44_fu_915_p2;
                slt45_reg_2004 <= slt45_fu_926_p2;
                slt46_reg_2009 <= slt46_fu_931_p2;
                slt47_reg_2014 <= slt47_fu_942_p2;
                slt48_reg_2019 <= slt48_fu_947_p2;
                slt49_reg_2024 <= slt49_fu_958_p2;
                slt50_reg_2029 <= slt50_fu_963_p2;
                slt51_reg_2034 <= slt51_fu_974_p2;
                slt52_reg_2039 <= slt52_fu_979_p2;
                slt_reg_1944 <= slt_fu_830_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                emsub_V_2_reg_1632 <= emsub_V_2_fu_574_p2;
                emsub_V_3_reg_1653 <= emsub_V_3_fu_606_p2;
                emsub_V_4_reg_1674 <= emsub_V_4_fu_638_p2;
                emsub_V_5_reg_1695 <= emsub_V_5_fu_670_p2;
                emsub_V_6_reg_1716 <= emsub_V_6_fu_702_p2;
                emsub_V_7_reg_1737 <= emsub_V_7_fu_734_p2;
                emsub_V_8_reg_1758 <= emsub_V_8_fu_766_p2;
                emsub_V_9_reg_1779 <= emsub_V_9_fu_798_p2;
                emsub_V_reg_1590 <= emsub_V_fu_510_p2;
                emsub_V_s_reg_1611 <= emsub_V_s_fu_542_p2;
                ptsub_V_1_reg_1605 <= ptsub_V_1_fu_536_p2;
                ptsub_V_2_reg_1626 <= ptsub_V_2_fu_568_p2;
                ptsub_V_3_reg_1647 <= ptsub_V_3_fu_600_p2;
                ptsub_V_4_reg_1668 <= ptsub_V_4_fu_632_p2;
                ptsub_V_5_reg_1689 <= ptsub_V_5_fu_664_p2;
                ptsub_V_6_reg_1710 <= ptsub_V_6_fu_696_p2;
                ptsub_V_7_reg_1731 <= ptsub_V_7_fu_728_p2;
                ptsub_V_8_reg_1752 <= ptsub_V_8_fu_760_p2;
                ptsub_V_9_reg_1773 <= ptsub_V_9_fu_792_p2;
                ptsub_V_reg_1584 <= ptsub_V_fu_504_p2;
                tmp_58_reg_1600 <= calo_0_hwEmPt_V_rea(15 downto 3);
                tmp_59_reg_1616 <= calo_1_hwPt_V_read(15 downto 4);
                tmp_60_reg_1621 <= calo_1_hwEmPt_V_rea(15 downto 3);
                tmp_61_reg_1637 <= calo_2_hwPt_V_read(15 downto 4);
                tmp_62_reg_1642 <= calo_2_hwEmPt_V_rea(15 downto 3);
                tmp_63_reg_1658 <= calo_3_hwPt_V_read(15 downto 4);
                tmp_64_reg_1663 <= calo_3_hwEmPt_V_rea(15 downto 3);
                tmp_65_reg_1679 <= calo_4_hwPt_V_read(15 downto 4);
                tmp_66_reg_1684 <= calo_4_hwEmPt_V_rea(15 downto 3);
                tmp_67_reg_1700 <= calo_5_hwPt_V_read(15 downto 4);
                tmp_68_reg_1705 <= calo_5_hwEmPt_V_rea(15 downto 3);
                tmp_69_reg_1721 <= calo_6_hwPt_V_read(15 downto 4);
                tmp_70_reg_1726 <= calo_6_hwEmPt_V_rea(15 downto 3);
                tmp_71_reg_1742 <= calo_7_hwPt_V_read(15 downto 4);
                tmp_72_reg_1747 <= calo_7_hwEmPt_V_rea(15 downto 3);
                tmp_73_reg_1763 <= calo_8_hwPt_V_read(15 downto 4);
                tmp_74_reg_1768 <= calo_8_hwEmPt_V_rea(15 downto 3);
                tmp_75_reg_1784 <= calo_9_hwPt_V_read(15 downto 4);
                tmp_76_reg_1789 <= calo_9_hwEmPt_V_rea(15 downto 3);
                tmp_s_reg_1595 <= calo_0_hwPt_V_read(15 downto 4);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= calo_out_0_hwPt_V_w_fu_1012_p3;
    ap_return_1 <= calo_out_1_hwPt_V_w_fu_1054_p3;
    ap_return_10 <= calo_out_0_hwEta_V_s_fu_1005_p3;
    ap_return_11 <= calo_out_1_hwEta_V_s_fu_1047_p3;
    ap_return_12 <= calo_out_2_hwEta_V_s_fu_1096_p3;
    ap_return_13 <= calo_out_3_hwEta_V_s_fu_1138_p3;
    ap_return_14 <= calo_out_4_hwEta_V_s_fu_1180_p3;
    ap_return_15 <= calo_out_5_hwEta_V_s_fu_1222_p3;
    ap_return_16 <= calo_out_6_hwEta_V_s_fu_1264_p3;
    ap_return_17 <= calo_out_7_hwEta_V_s_fu_1306_p3;
    ap_return_18 <= calo_out_8_hwEta_V_s_fu_1348_p3;
    ap_return_19 <= calo_out_9_hwEta_V_s_fu_1390_p3;
    ap_return_2 <= calo_out_2_hwPt_V_w_fu_1089_p3;
    ap_return_20 <= calo_out_0_hwPhi_V_s_fu_1019_p3;
    ap_return_21 <= calo_out_1_hwPhi_V_s_fu_1061_p3;
    ap_return_22 <= calo_out_2_hwPhi_V_s_fu_1103_p3;
    ap_return_23 <= calo_out_3_hwPhi_V_s_fu_1145_p3;
    ap_return_24 <= calo_out_4_hwPhi_V_s_fu_1187_p3;
    ap_return_25 <= calo_out_5_hwPhi_V_s_fu_1229_p3;
    ap_return_26 <= calo_out_6_hwPhi_V_s_fu_1271_p3;
    ap_return_27 <= calo_out_7_hwPhi_V_s_fu_1313_p3;
    ap_return_28 <= calo_out_8_hwPhi_V_s_fu_1355_p3;
    ap_return_29 <= calo_out_9_hwPhi_V_s_fu_1397_p3;
    ap_return_3 <= calo_out_3_hwPt_V_w_fu_1131_p3;
    ap_return_4 <= calo_out_4_hwPt_V_w_fu_1173_p3;
    ap_return_5 <= calo_out_5_hwPt_V_w_fu_1215_p3;
    ap_return_6 <= calo_out_6_hwPt_V_w_fu_1257_p3;
    ap_return_7 <= calo_out_7_hwPt_V_w_fu_1299_p3;
    ap_return_8 <= calo_out_8_hwPt_V_w_fu_1341_p3;
    ap_return_9 <= calo_out_9_hwPt_V_w_fu_1383_p3;
    calo_out_0_hwEta_V_s_fu_1005_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_fu_999_p2(0) = '1') else 
        calo_0_hwEta_V_read_7_reg_1939;
    calo_out_0_hwPhi_V_s_fu_1019_p3 <= 
        ap_const_lv10_0 when (sel_tmp3_fu_999_p2(0) = '1') else 
        calo_0_hwPhi_V_read_7_reg_1889;
    calo_out_0_hwPt_V_w_fu_1012_p3 <= 
        ap_const_lv16_0 when (sel_tmp3_fu_999_p2(0) = '1') else 
        ptsub_V_reg_1584;
    calo_out_1_hwEta_V_s_fu_1047_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_fu_1041_p2(0) = '1') else 
        calo_1_hwEta_V_read_7_reg_1934;
    calo_out_1_hwPhi_V_s_fu_1061_p3 <= 
        ap_const_lv10_0 when (sel_tmp18_fu_1041_p2(0) = '1') else 
        calo_1_hwPhi_V_read_7_reg_1884;
    calo_out_1_hwPt_V_w_fu_1054_p3 <= 
        ap_const_lv16_0 when (sel_tmp18_fu_1041_p2(0) = '1') else 
        ptsub_V_1_reg_1605;
    calo_out_2_hwEta_V_s_fu_1096_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_fu_1083_p2(0) = '1') else 
        calo_2_hwEta_V_read_7_reg_1929;
    calo_out_2_hwPhi_V_s_fu_1103_p3 <= 
        ap_const_lv10_0 when (sel_tmp33_fu_1083_p2(0) = '1') else 
        calo_2_hwPhi_V_read_7_reg_1879;
    calo_out_2_hwPt_V_w_fu_1089_p3 <= 
        ap_const_lv16_0 when (sel_tmp33_fu_1083_p2(0) = '1') else 
        ptsub_V_2_reg_1626;
    calo_out_3_hwEta_V_s_fu_1138_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_fu_1125_p2(0) = '1') else 
        calo_3_hwEta_V_read_7_reg_1924;
    calo_out_3_hwPhi_V_s_fu_1145_p3 <= 
        ap_const_lv10_0 when (sel_tmp48_fu_1125_p2(0) = '1') else 
        calo_3_hwPhi_V_read_7_reg_1874;
    calo_out_3_hwPt_V_w_fu_1131_p3 <= 
        ap_const_lv16_0 when (sel_tmp48_fu_1125_p2(0) = '1') else 
        ptsub_V_3_reg_1647;
    calo_out_4_hwEta_V_s_fu_1180_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_fu_1167_p2(0) = '1') else 
        calo_4_hwEta_V_read_7_reg_1919;
    calo_out_4_hwPhi_V_s_fu_1187_p3 <= 
        ap_const_lv10_0 when (sel_tmp63_fu_1167_p2(0) = '1') else 
        calo_4_hwPhi_V_read_7_reg_1869;
    calo_out_4_hwPt_V_w_fu_1173_p3 <= 
        ap_const_lv16_0 when (sel_tmp63_fu_1167_p2(0) = '1') else 
        ptsub_V_4_reg_1668;
    calo_out_5_hwEta_V_s_fu_1222_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_fu_1209_p2(0) = '1') else 
        calo_5_hwEta_V_read_7_reg_1914;
    calo_out_5_hwPhi_V_s_fu_1229_p3 <= 
        ap_const_lv10_0 when (sel_tmp78_fu_1209_p2(0) = '1') else 
        calo_5_hwPhi_V_read_7_reg_1864;
    calo_out_5_hwPt_V_w_fu_1215_p3 <= 
        ap_const_lv16_0 when (sel_tmp78_fu_1209_p2(0) = '1') else 
        ptsub_V_5_reg_1689;
    calo_out_6_hwEta_V_s_fu_1264_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_fu_1251_p2(0) = '1') else 
        calo_6_hwEta_V_read_7_reg_1909;
    calo_out_6_hwPhi_V_s_fu_1271_p3 <= 
        ap_const_lv10_0 when (sel_tmp93_fu_1251_p2(0) = '1') else 
        calo_6_hwPhi_V_read_7_reg_1859;
    calo_out_6_hwPt_V_w_fu_1257_p3 <= 
        ap_const_lv16_0 when (sel_tmp93_fu_1251_p2(0) = '1') else 
        ptsub_V_6_reg_1710;
    calo_out_7_hwEta_V_s_fu_1306_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_fu_1293_p2(0) = '1') else 
        calo_7_hwEta_V_read_7_reg_1904;
    calo_out_7_hwPhi_V_s_fu_1313_p3 <= 
        ap_const_lv10_0 when (sel_tmp108_fu_1293_p2(0) = '1') else 
        calo_7_hwPhi_V_read_7_reg_1854;
    calo_out_7_hwPt_V_w_fu_1299_p3 <= 
        ap_const_lv16_0 when (sel_tmp108_fu_1293_p2(0) = '1') else 
        ptsub_V_7_reg_1731;
    calo_out_8_hwEta_V_s_fu_1348_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_fu_1335_p2(0) = '1') else 
        calo_8_hwEta_V_read_7_reg_1899;
    calo_out_8_hwPhi_V_s_fu_1355_p3 <= 
        ap_const_lv10_0 when (sel_tmp123_fu_1335_p2(0) = '1') else 
        calo_8_hwPhi_V_read_7_reg_1849;
    calo_out_8_hwPt_V_w_fu_1341_p3 <= 
        ap_const_lv16_0 when (sel_tmp123_fu_1335_p2(0) = '1') else 
        ptsub_V_8_reg_1752;
    calo_out_9_hwEta_V_s_fu_1390_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_fu_1377_p2(0) = '1') else 
        calo_9_hwEta_V_read_7_reg_1894;
    calo_out_9_hwPhi_V_s_fu_1397_p3 <= 
        ap_const_lv10_0 when (sel_tmp138_fu_1377_p2(0) = '1') else 
        calo_9_hwPhi_V_read_7_reg_1844;
    calo_out_9_hwPt_V_w_fu_1383_p3 <= 
        ap_const_lv16_0 when (sel_tmp138_fu_1377_p2(0) = '1') else 
        ptsub_V_9_reg_1773;
    emsub_V_2_fu_574_p2 <= std_logic_vector(unsigned(calo_2_hwEmPt_V_rea) - unsigned(sumem_2_V_read));
    emsub_V_3_fu_606_p2 <= std_logic_vector(unsigned(calo_3_hwEmPt_V_rea) - unsigned(sumem_3_V_read));
    emsub_V_4_fu_638_p2 <= std_logic_vector(unsigned(calo_4_hwEmPt_V_rea) - unsigned(sumem_4_V_read));
    emsub_V_5_fu_670_p2 <= std_logic_vector(unsigned(calo_5_hwEmPt_V_rea) - unsigned(sumem_5_V_read));
    emsub_V_6_fu_702_p2 <= std_logic_vector(unsigned(calo_6_hwEmPt_V_rea) - unsigned(sumem_6_V_read));
    emsub_V_7_fu_734_p2 <= std_logic_vector(unsigned(calo_7_hwEmPt_V_rea) - unsigned(sumem_7_V_read));
    emsub_V_8_fu_766_p2 <= std_logic_vector(unsigned(calo_8_hwEmPt_V_rea) - unsigned(sumem_8_V_read));
    emsub_V_9_fu_798_p2 <= std_logic_vector(unsigned(calo_9_hwEmPt_V_rea) - unsigned(sumem_9_V_read));
    emsub_V_fu_510_p2 <= std_logic_vector(unsigned(calo_0_hwEmPt_V_rea) - unsigned(sumem_0_V_read));
    emsub_V_s_fu_542_p2 <= std_logic_vector(unsigned(calo_1_hwEmPt_V_rea) - unsigned(sumem_1_V_read));
    ptsub_V_1_fu_536_p2 <= std_logic_vector(unsigned(calo_1_hwPt_V_read) - unsigned(sumem_1_V_read));
    ptsub_V_2_fu_568_p2 <= std_logic_vector(unsigned(calo_2_hwPt_V_read) - unsigned(sumem_2_V_read));
    ptsub_V_3_fu_600_p2 <= std_logic_vector(unsigned(calo_3_hwPt_V_read) - unsigned(sumem_3_V_read));
    ptsub_V_4_fu_632_p2 <= std_logic_vector(unsigned(calo_4_hwPt_V_read) - unsigned(sumem_4_V_read));
    ptsub_V_5_fu_664_p2 <= std_logic_vector(unsigned(calo_5_hwPt_V_read) - unsigned(sumem_5_V_read));
    ptsub_V_6_fu_696_p2 <= std_logic_vector(unsigned(calo_6_hwPt_V_read) - unsigned(sumem_6_V_read));
    ptsub_V_7_fu_728_p2 <= std_logic_vector(unsigned(calo_7_hwPt_V_read) - unsigned(sumem_7_V_read));
    ptsub_V_8_fu_760_p2 <= std_logic_vector(unsigned(calo_8_hwPt_V_read) - unsigned(sumem_8_V_read));
    ptsub_V_9_fu_792_p2 <= std_logic_vector(unsigned(calo_9_hwPt_V_read) - unsigned(sumem_9_V_read));
    ptsub_V_fu_504_p2 <= std_logic_vector(unsigned(calo_0_hwPt_V_read) - unsigned(sumem_0_V_read));
        r_V_1_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_59_reg_1616),16));

        r_V_2_fu_856_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_61_reg_1637),16));

        r_V_3_fu_872_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_63_reg_1658),16));

        r_V_4_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_65_reg_1679),16));

        r_V_5_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_67_reg_1700),16));

        r_V_6_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_69_reg_1721),16));

        r_V_7_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_71_reg_1742),16));

        r_V_8_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_73_reg_1763),16));

        r_V_9_1_fu_843_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_60_reg_1621),16));

        r_V_9_2_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_62_reg_1642),16));

        r_V_9_3_fu_875_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_64_reg_1663),16));

        r_V_9_4_fu_891_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_66_reg_1684),16));

        r_V_9_5_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_68_reg_1705),16));

        r_V_9_6_fu_923_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_70_reg_1726),16));

        r_V_9_7_fu_939_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_72_reg_1747),16));

        r_V_9_8_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_74_reg_1768),16));

        r_V_9_9_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_76_reg_1789),16));

        r_V_9_fu_827_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_58_reg_1600),16));

        r_V_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_reg_1595),16));

        r_V_s_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_75_reg_1784),16));

    rev34_fu_989_p2 <= (slt34_reg_1949 xor ap_const_lv1_1);
    rev35_fu_1026_p2 <= (slt35_reg_1954 xor ap_const_lv1_1);
    rev36_fu_1031_p2 <= (slt36_reg_1959 xor ap_const_lv1_1);
    rev37_fu_1068_p2 <= (slt37_reg_1964 xor ap_const_lv1_1);
    rev38_fu_1073_p2 <= (slt38_reg_1969 xor ap_const_lv1_1);
    rev39_fu_1110_p2 <= (slt39_reg_1974 xor ap_const_lv1_1);
    rev40_fu_1115_p2 <= (slt40_reg_1979 xor ap_const_lv1_1);
    rev41_fu_1152_p2 <= (slt41_reg_1984 xor ap_const_lv1_1);
    rev42_fu_1157_p2 <= (slt42_reg_1989 xor ap_const_lv1_1);
    rev43_fu_1194_p2 <= (slt43_reg_1994 xor ap_const_lv1_1);
    rev44_fu_1199_p2 <= (slt44_reg_1999 xor ap_const_lv1_1);
    rev45_fu_1236_p2 <= (slt45_reg_2004 xor ap_const_lv1_1);
    rev46_fu_1241_p2 <= (slt46_reg_2009 xor ap_const_lv1_1);
    rev47_fu_1278_p2 <= (slt47_reg_2014 xor ap_const_lv1_1);
    rev48_fu_1283_p2 <= (slt48_reg_2019 xor ap_const_lv1_1);
    rev49_fu_1320_p2 <= (slt49_reg_2024 xor ap_const_lv1_1);
    rev50_fu_1325_p2 <= (slt50_reg_2029 xor ap_const_lv1_1);
    rev51_fu_1362_p2 <= (slt51_reg_2034 xor ap_const_lv1_1);
    rev52_fu_1367_p2 <= (slt52_reg_2039 xor ap_const_lv1_1);
    rev_fu_984_p2 <= (slt_reg_1944 xor ap_const_lv1_1);
    sel_tmp107_fu_1288_p2 <= (rev48_fu_1283_p2 and calo_7_hwIsEM_read_1_reg_1804);
    sel_tmp108_fu_1293_p2 <= (sel_tmp107_fu_1288_p2 or rev47_fu_1278_p2);
    sel_tmp122_fu_1330_p2 <= (rev50_fu_1325_p2 and calo_8_hwIsEM_read_1_reg_1799);
    sel_tmp123_fu_1335_p2 <= (sel_tmp122_fu_1330_p2 or rev49_fu_1320_p2);
    sel_tmp137_fu_1372_p2 <= (rev52_fu_1367_p2 and calo_9_hwIsEM_read_1_reg_1794);
    sel_tmp138_fu_1377_p2 <= (sel_tmp137_fu_1372_p2 or rev51_fu_1362_p2);
    sel_tmp17_fu_1036_p2 <= (rev36_fu_1031_p2 and calo_1_hwIsEM_read_1_reg_1834);
    sel_tmp18_fu_1041_p2 <= (sel_tmp17_fu_1036_p2 or rev35_fu_1026_p2);
    sel_tmp2_fu_994_p2 <= (rev34_fu_989_p2 and calo_0_hwIsEM_read_1_reg_1839);
    sel_tmp32_fu_1078_p2 <= (rev38_fu_1073_p2 and calo_2_hwIsEM_read_1_reg_1829);
    sel_tmp33_fu_1083_p2 <= (sel_tmp32_fu_1078_p2 or rev37_fu_1068_p2);
    sel_tmp3_fu_999_p2 <= (sel_tmp2_fu_994_p2 or rev_fu_984_p2);
    sel_tmp47_fu_1120_p2 <= (rev40_fu_1115_p2 and calo_3_hwIsEM_read_1_reg_1824);
    sel_tmp48_fu_1125_p2 <= (sel_tmp47_fu_1120_p2 or rev39_fu_1110_p2);
    sel_tmp62_fu_1162_p2 <= (rev42_fu_1157_p2 and calo_4_hwIsEM_read_1_reg_1819);
    sel_tmp63_fu_1167_p2 <= (sel_tmp62_fu_1162_p2 or rev41_fu_1152_p2);
    sel_tmp77_fu_1204_p2 <= (rev44_fu_1199_p2 and calo_5_hwIsEM_read_1_reg_1814);
    sel_tmp78_fu_1209_p2 <= (sel_tmp77_fu_1204_p2 or rev43_fu_1194_p2);
    sel_tmp92_fu_1246_p2 <= (rev46_fu_1241_p2 and calo_6_hwIsEM_read_1_reg_1809);
    sel_tmp93_fu_1251_p2 <= (sel_tmp92_fu_1246_p2 or rev45_fu_1236_p2);
    slt34_fu_835_p2 <= "1" when (signed(r_V_9_fu_827_p1) < signed(emsub_V_reg_1590)) else "0";
    slt35_fu_846_p2 <= "1" when (signed(r_V_1_fu_840_p1) < signed(ptsub_V_1_reg_1605)) else "0";
    slt36_fu_851_p2 <= "1" when (signed(r_V_9_1_fu_843_p1) < signed(emsub_V_s_reg_1611)) else "0";
    slt37_fu_862_p2 <= "1" when (signed(r_V_2_fu_856_p1) < signed(ptsub_V_2_reg_1626)) else "0";
    slt38_fu_867_p2 <= "1" when (signed(r_V_9_2_fu_859_p1) < signed(emsub_V_2_reg_1632)) else "0";
    slt39_fu_878_p2 <= "1" when (signed(r_V_3_fu_872_p1) < signed(ptsub_V_3_reg_1647)) else "0";
    slt40_fu_883_p2 <= "1" when (signed(r_V_9_3_fu_875_p1) < signed(emsub_V_3_reg_1653)) else "0";
    slt41_fu_894_p2 <= "1" when (signed(r_V_4_fu_888_p1) < signed(ptsub_V_4_reg_1668)) else "0";
    slt42_fu_899_p2 <= "1" when (signed(r_V_9_4_fu_891_p1) < signed(emsub_V_4_reg_1674)) else "0";
    slt43_fu_910_p2 <= "1" when (signed(r_V_5_fu_904_p1) < signed(ptsub_V_5_reg_1689)) else "0";
    slt44_fu_915_p2 <= "1" when (signed(r_V_9_5_fu_907_p1) < signed(emsub_V_5_reg_1695)) else "0";
    slt45_fu_926_p2 <= "1" when (signed(r_V_6_fu_920_p1) < signed(ptsub_V_6_reg_1710)) else "0";
    slt46_fu_931_p2 <= "1" when (signed(r_V_9_6_fu_923_p1) < signed(emsub_V_6_reg_1716)) else "0";
    slt47_fu_942_p2 <= "1" when (signed(r_V_7_fu_936_p1) < signed(ptsub_V_7_reg_1731)) else "0";
    slt48_fu_947_p2 <= "1" when (signed(r_V_9_7_fu_939_p1) < signed(emsub_V_7_reg_1737)) else "0";
    slt49_fu_958_p2 <= "1" when (signed(r_V_8_fu_952_p1) < signed(ptsub_V_8_reg_1752)) else "0";
    slt50_fu_963_p2 <= "1" when (signed(r_V_9_8_fu_955_p1) < signed(emsub_V_8_reg_1758)) else "0";
    slt51_fu_974_p2 <= "1" when (signed(r_V_s_fu_968_p1) < signed(ptsub_V_9_reg_1773)) else "0";
    slt52_fu_979_p2 <= "1" when (signed(r_V_9_9_fu_971_p1) < signed(emsub_V_9_reg_1779)) else "0";
    slt_fu_830_p2 <= "1" when (signed(r_V_fu_824_p1) < signed(ptsub_V_reg_1584)) else "0";
end behav;
