-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity em2calo_link is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    emcalo_0_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_1_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_2_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_3_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_4_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_5_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_6_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_7_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_8_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_9_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
    emcalo_0_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_1_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_2_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_3_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_4_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_5_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_6_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_7_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_8_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_9_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_0_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_1_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_2_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_3_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_4_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_5_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_6_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_7_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_8_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    emcalo_9_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_0_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_1_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_2_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_3_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_4_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_5_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_6_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_7_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_8_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_9_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_0_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_1_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_2_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_3_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_4_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_5_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_6_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_7_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_8_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_9_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
    hadcalo_0_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_1_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_2_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_3_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_4_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_5_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_6_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_7_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_8_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    hadcalo_9_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of em2calo_link is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal ap_block_state12_pp0_stage5_iter1 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal drvals_0_0_V_reg_1196 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state10_pp0_stage3_iter1 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal drvals_0_1_V_reg_1201 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_2_V_reg_1206 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_3_V_reg_1211 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_4_V_reg_1216 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_5_V_reg_1221 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_6_V_reg_1226 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_7_V_reg_1231 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_8_V_reg_1236 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_0_9_V_reg_1241 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_0_V_reg_1246 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_1_V_reg_1251 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_2_V_reg_1256 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_3_V_reg_1261 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_4_V_reg_1266 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_5_V_reg_1271 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_6_V_reg_1276 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_7_V_reg_1281 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_8_V_reg_1286 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_1_9_V_reg_1291 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_0_V_reg_1296 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_1_V_reg_1301 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_2_V_reg_1306 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_3_V_reg_1311 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_4_V_reg_1316 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_5_V_reg_1321 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_6_V_reg_1326 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_7_V_reg_1331 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_8_V_reg_1336 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_2_9_V_reg_1341 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_0_V_reg_1346 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_1_V_reg_1351 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_2_V_reg_1356 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_3_V_reg_1361 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_4_V_reg_1366 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_5_V_reg_1371 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_6_V_reg_1376 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_7_V_reg_1381 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_8_V_reg_1386 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_3_9_V_reg_1391 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_0_V_reg_1396 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_1_V_reg_1401 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_2_V_reg_1406 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_3_V_reg_1411 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_4_V_reg_1416 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_5_V_reg_1421 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_6_V_reg_1426 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_7_V_reg_1431 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_8_V_reg_1436 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_4_9_V_reg_1441 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_0_V_reg_1446 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_1_V_reg_1451 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_2_V_reg_1456 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_3_V_reg_1461 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_4_V_reg_1466 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_5_V_reg_1471 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_6_V_reg_1476 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_7_V_reg_1481 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_8_V_reg_1486 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_5_9_V_reg_1491 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_0_V_reg_1496 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_1_V_reg_1501 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_2_V_reg_1506 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_3_V_reg_1511 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_4_V_reg_1516 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_5_V_reg_1521 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_6_V_reg_1526 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_7_V_reg_1531 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_8_V_reg_1536 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_6_9_V_reg_1541 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_0_V_reg_1546 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_1_V_reg_1551 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_2_V_reg_1556 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_3_V_reg_1561 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_4_V_reg_1566 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_5_V_reg_1571 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_6_V_reg_1576 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_7_V_reg_1581 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_8_V_reg_1586 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_7_9_V_reg_1591 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_0_V_reg_1596 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_1_V_reg_1601 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_2_V_reg_1606 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_3_V_reg_1611 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_4_V_reg_1616 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_5_V_reg_1621 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_6_V_reg_1626 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_7_V_reg_1631 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_8_V_reg_1636 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_8_9_V_reg_1641 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_0_V_reg_1646 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_1_V_reg_1651 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_2_V_reg_1656 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_3_V_reg_1661 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_4_V_reg_1666 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_5_V_reg_1671 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_6_V_reg_1676 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_7_V_reg_1681 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_8_V_reg_1686 : STD_LOGIC_VECTOR (9 downto 0);
    signal drvals_9_9_V_reg_1691 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state15_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal grp_em2calo_drvals_525_s_fu_488_ap_start : STD_LOGIC;
    signal grp_em2calo_drvals_525_s_fu_488_ap_done : STD_LOGIC;
    signal grp_em2calo_drvals_525_s_fu_488_ap_idle : STD_LOGIC;
    signal grp_em2calo_drvals_525_s_fu_488_ap_ready : STD_LOGIC;
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_5 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_6 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_7 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_8 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_9 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_10 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_11 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_12 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_13 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_14 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_15 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_16 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_17 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_18 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_19 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_20 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_21 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_22 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_23 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_24 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_25 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_26 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_27 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_28 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_29 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_30 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_31 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_32 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_33 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_34 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_35 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_36 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_37 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_38 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_39 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_40 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_41 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_42 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_43 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_44 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_45 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_46 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_47 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_48 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_49 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_50 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_51 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_52 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_53 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_54 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_55 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_56 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_57 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_58 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_59 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_60 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_61 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_62 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_63 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_64 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_65 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_66 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_67 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_68 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_69 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_70 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_71 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_72 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_73 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_74 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_75 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_76 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_77 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_78 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_79 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_80 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_81 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_82 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_83 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_84 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_85 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_86 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_87 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_88 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_89 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_90 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_91 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_92 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_93 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_94 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_95 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_96 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_97 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_98 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_em2calo_drvals_525_s_fu_488_ap_return_99 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_start : STD_LOGIC;
    signal grp_pick_closest_1_fu_612_ap_done : STD_LOGIC;
    signal grp_pick_closest_1_fu_612_ap_idle : STD_LOGIC;
    signal grp_pick_closest_1_fu_612_ap_ready : STD_LOGIC;
    signal grp_pick_closest_1_fu_612_ap_return_0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_4 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_5 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_6 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_7 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_8 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_return_9 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_pick_closest_1_fu_612_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state14_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_state11_pp0_stage4_iter1 : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;

    component em2calo_drvals_525_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        hadcalo_0_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_1_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_2_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_3_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_4_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_5_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_6_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_7_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_8_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_9_hwEta_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_0_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_1_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_2_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_3_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_4_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_5_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_6_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_7_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_8_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_9_hwPhi_V_r : IN STD_LOGIC_VECTOR (9 downto 0);
        hadcalo_0_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_1_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_2_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_3_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_4_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_5_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_6_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_7_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_8_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        hadcalo_9_hwEmPt_V_s : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_0_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_1_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_2_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_3_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_4_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_5_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_6_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_7_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_8_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_9_hwPt_V_rea : IN STD_LOGIC_VECTOR (15 downto 0);
        emcalo_0_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_1_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_2_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_3_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_4_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_5_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_6_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_7_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_8_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_9_hwEta_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_0_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_1_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_2_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_3_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_4_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_5_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_6_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_7_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_8_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        emcalo_9_hwPhi_V_re : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_32 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_33 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_34 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_35 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_36 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_37 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_38 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_39 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_40 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_41 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_42 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_43 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_44 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_45 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_46 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_47 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_48 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_49 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_50 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_51 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_52 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_53 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_54 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_55 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_56 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_57 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_58 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_59 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_60 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_61 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_62 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_63 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_64 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_65 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_66 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_67 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_68 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_69 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_70 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_71 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_72 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_73 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_74 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_75 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_76 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_77 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_78 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_79 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_80 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_81 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_82 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_83 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_84 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_85 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_86 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_87 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_88 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_89 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_90 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_91 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_92 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_93 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_94 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_95 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_96 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_97 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_98 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_99 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component pick_closest_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        calo_track_drval_0_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_0_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_1_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_2_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_3_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_4_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_5_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_6_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_7_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_8_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_1_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_2_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_3_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_4_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_5_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_6_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_7_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_8_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        calo_track_drval_9_9_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (9 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;



begin
    grp_em2calo_drvals_525_s_fu_488 : component em2calo_drvals_525_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_em2calo_drvals_525_s_fu_488_ap_start,
        ap_done => grp_em2calo_drvals_525_s_fu_488_ap_done,
        ap_idle => grp_em2calo_drvals_525_s_fu_488_ap_idle,
        ap_ready => grp_em2calo_drvals_525_s_fu_488_ap_ready,
        hadcalo_0_hwEta_V_r => hadcalo_0_hwEta_V_r,
        hadcalo_1_hwEta_V_r => hadcalo_1_hwEta_V_r,
        hadcalo_2_hwEta_V_r => hadcalo_2_hwEta_V_r,
        hadcalo_3_hwEta_V_r => hadcalo_3_hwEta_V_r,
        hadcalo_4_hwEta_V_r => hadcalo_4_hwEta_V_r,
        hadcalo_5_hwEta_V_r => hadcalo_5_hwEta_V_r,
        hadcalo_6_hwEta_V_r => hadcalo_6_hwEta_V_r,
        hadcalo_7_hwEta_V_r => hadcalo_7_hwEta_V_r,
        hadcalo_8_hwEta_V_r => hadcalo_8_hwEta_V_r,
        hadcalo_9_hwEta_V_r => hadcalo_9_hwEta_V_r,
        hadcalo_0_hwPhi_V_r => hadcalo_0_hwPhi_V_r,
        hadcalo_1_hwPhi_V_r => hadcalo_1_hwPhi_V_r,
        hadcalo_2_hwPhi_V_r => hadcalo_2_hwPhi_V_r,
        hadcalo_3_hwPhi_V_r => hadcalo_3_hwPhi_V_r,
        hadcalo_4_hwPhi_V_r => hadcalo_4_hwPhi_V_r,
        hadcalo_5_hwPhi_V_r => hadcalo_5_hwPhi_V_r,
        hadcalo_6_hwPhi_V_r => hadcalo_6_hwPhi_V_r,
        hadcalo_7_hwPhi_V_r => hadcalo_7_hwPhi_V_r,
        hadcalo_8_hwPhi_V_r => hadcalo_8_hwPhi_V_r,
        hadcalo_9_hwPhi_V_r => hadcalo_9_hwPhi_V_r,
        hadcalo_0_hwEmPt_V_s => hadcalo_0_hwEmPt_V_s,
        hadcalo_1_hwEmPt_V_s => hadcalo_1_hwEmPt_V_s,
        hadcalo_2_hwEmPt_V_s => hadcalo_2_hwEmPt_V_s,
        hadcalo_3_hwEmPt_V_s => hadcalo_3_hwEmPt_V_s,
        hadcalo_4_hwEmPt_V_s => hadcalo_4_hwEmPt_V_s,
        hadcalo_5_hwEmPt_V_s => hadcalo_5_hwEmPt_V_s,
        hadcalo_6_hwEmPt_V_s => hadcalo_6_hwEmPt_V_s,
        hadcalo_7_hwEmPt_V_s => hadcalo_7_hwEmPt_V_s,
        hadcalo_8_hwEmPt_V_s => hadcalo_8_hwEmPt_V_s,
        hadcalo_9_hwEmPt_V_s => hadcalo_9_hwEmPt_V_s,
        emcalo_0_hwPt_V_rea => emcalo_0_hwPt_V_rea,
        emcalo_1_hwPt_V_rea => emcalo_1_hwPt_V_rea,
        emcalo_2_hwPt_V_rea => emcalo_2_hwPt_V_rea,
        emcalo_3_hwPt_V_rea => emcalo_3_hwPt_V_rea,
        emcalo_4_hwPt_V_rea => emcalo_4_hwPt_V_rea,
        emcalo_5_hwPt_V_rea => emcalo_5_hwPt_V_rea,
        emcalo_6_hwPt_V_rea => emcalo_6_hwPt_V_rea,
        emcalo_7_hwPt_V_rea => emcalo_7_hwPt_V_rea,
        emcalo_8_hwPt_V_rea => emcalo_8_hwPt_V_rea,
        emcalo_9_hwPt_V_rea => emcalo_9_hwPt_V_rea,
        emcalo_0_hwEta_V_re => emcalo_0_hwEta_V_re,
        emcalo_1_hwEta_V_re => emcalo_1_hwEta_V_re,
        emcalo_2_hwEta_V_re => emcalo_2_hwEta_V_re,
        emcalo_3_hwEta_V_re => emcalo_3_hwEta_V_re,
        emcalo_4_hwEta_V_re => emcalo_4_hwEta_V_re,
        emcalo_5_hwEta_V_re => emcalo_5_hwEta_V_re,
        emcalo_6_hwEta_V_re => emcalo_6_hwEta_V_re,
        emcalo_7_hwEta_V_re => emcalo_7_hwEta_V_re,
        emcalo_8_hwEta_V_re => emcalo_8_hwEta_V_re,
        emcalo_9_hwEta_V_re => emcalo_9_hwEta_V_re,
        emcalo_0_hwPhi_V_re => emcalo_0_hwPhi_V_re,
        emcalo_1_hwPhi_V_re => emcalo_1_hwPhi_V_re,
        emcalo_2_hwPhi_V_re => emcalo_2_hwPhi_V_re,
        emcalo_3_hwPhi_V_re => emcalo_3_hwPhi_V_re,
        emcalo_4_hwPhi_V_re => emcalo_4_hwPhi_V_re,
        emcalo_5_hwPhi_V_re => emcalo_5_hwPhi_V_re,
        emcalo_6_hwPhi_V_re => emcalo_6_hwPhi_V_re,
        emcalo_7_hwPhi_V_re => emcalo_7_hwPhi_V_re,
        emcalo_8_hwPhi_V_re => emcalo_8_hwPhi_V_re,
        emcalo_9_hwPhi_V_re => emcalo_9_hwPhi_V_re,
        ap_return_0 => grp_em2calo_drvals_525_s_fu_488_ap_return_0,
        ap_return_1 => grp_em2calo_drvals_525_s_fu_488_ap_return_1,
        ap_return_2 => grp_em2calo_drvals_525_s_fu_488_ap_return_2,
        ap_return_3 => grp_em2calo_drvals_525_s_fu_488_ap_return_3,
        ap_return_4 => grp_em2calo_drvals_525_s_fu_488_ap_return_4,
        ap_return_5 => grp_em2calo_drvals_525_s_fu_488_ap_return_5,
        ap_return_6 => grp_em2calo_drvals_525_s_fu_488_ap_return_6,
        ap_return_7 => grp_em2calo_drvals_525_s_fu_488_ap_return_7,
        ap_return_8 => grp_em2calo_drvals_525_s_fu_488_ap_return_8,
        ap_return_9 => grp_em2calo_drvals_525_s_fu_488_ap_return_9,
        ap_return_10 => grp_em2calo_drvals_525_s_fu_488_ap_return_10,
        ap_return_11 => grp_em2calo_drvals_525_s_fu_488_ap_return_11,
        ap_return_12 => grp_em2calo_drvals_525_s_fu_488_ap_return_12,
        ap_return_13 => grp_em2calo_drvals_525_s_fu_488_ap_return_13,
        ap_return_14 => grp_em2calo_drvals_525_s_fu_488_ap_return_14,
        ap_return_15 => grp_em2calo_drvals_525_s_fu_488_ap_return_15,
        ap_return_16 => grp_em2calo_drvals_525_s_fu_488_ap_return_16,
        ap_return_17 => grp_em2calo_drvals_525_s_fu_488_ap_return_17,
        ap_return_18 => grp_em2calo_drvals_525_s_fu_488_ap_return_18,
        ap_return_19 => grp_em2calo_drvals_525_s_fu_488_ap_return_19,
        ap_return_20 => grp_em2calo_drvals_525_s_fu_488_ap_return_20,
        ap_return_21 => grp_em2calo_drvals_525_s_fu_488_ap_return_21,
        ap_return_22 => grp_em2calo_drvals_525_s_fu_488_ap_return_22,
        ap_return_23 => grp_em2calo_drvals_525_s_fu_488_ap_return_23,
        ap_return_24 => grp_em2calo_drvals_525_s_fu_488_ap_return_24,
        ap_return_25 => grp_em2calo_drvals_525_s_fu_488_ap_return_25,
        ap_return_26 => grp_em2calo_drvals_525_s_fu_488_ap_return_26,
        ap_return_27 => grp_em2calo_drvals_525_s_fu_488_ap_return_27,
        ap_return_28 => grp_em2calo_drvals_525_s_fu_488_ap_return_28,
        ap_return_29 => grp_em2calo_drvals_525_s_fu_488_ap_return_29,
        ap_return_30 => grp_em2calo_drvals_525_s_fu_488_ap_return_30,
        ap_return_31 => grp_em2calo_drvals_525_s_fu_488_ap_return_31,
        ap_return_32 => grp_em2calo_drvals_525_s_fu_488_ap_return_32,
        ap_return_33 => grp_em2calo_drvals_525_s_fu_488_ap_return_33,
        ap_return_34 => grp_em2calo_drvals_525_s_fu_488_ap_return_34,
        ap_return_35 => grp_em2calo_drvals_525_s_fu_488_ap_return_35,
        ap_return_36 => grp_em2calo_drvals_525_s_fu_488_ap_return_36,
        ap_return_37 => grp_em2calo_drvals_525_s_fu_488_ap_return_37,
        ap_return_38 => grp_em2calo_drvals_525_s_fu_488_ap_return_38,
        ap_return_39 => grp_em2calo_drvals_525_s_fu_488_ap_return_39,
        ap_return_40 => grp_em2calo_drvals_525_s_fu_488_ap_return_40,
        ap_return_41 => grp_em2calo_drvals_525_s_fu_488_ap_return_41,
        ap_return_42 => grp_em2calo_drvals_525_s_fu_488_ap_return_42,
        ap_return_43 => grp_em2calo_drvals_525_s_fu_488_ap_return_43,
        ap_return_44 => grp_em2calo_drvals_525_s_fu_488_ap_return_44,
        ap_return_45 => grp_em2calo_drvals_525_s_fu_488_ap_return_45,
        ap_return_46 => grp_em2calo_drvals_525_s_fu_488_ap_return_46,
        ap_return_47 => grp_em2calo_drvals_525_s_fu_488_ap_return_47,
        ap_return_48 => grp_em2calo_drvals_525_s_fu_488_ap_return_48,
        ap_return_49 => grp_em2calo_drvals_525_s_fu_488_ap_return_49,
        ap_return_50 => grp_em2calo_drvals_525_s_fu_488_ap_return_50,
        ap_return_51 => grp_em2calo_drvals_525_s_fu_488_ap_return_51,
        ap_return_52 => grp_em2calo_drvals_525_s_fu_488_ap_return_52,
        ap_return_53 => grp_em2calo_drvals_525_s_fu_488_ap_return_53,
        ap_return_54 => grp_em2calo_drvals_525_s_fu_488_ap_return_54,
        ap_return_55 => grp_em2calo_drvals_525_s_fu_488_ap_return_55,
        ap_return_56 => grp_em2calo_drvals_525_s_fu_488_ap_return_56,
        ap_return_57 => grp_em2calo_drvals_525_s_fu_488_ap_return_57,
        ap_return_58 => grp_em2calo_drvals_525_s_fu_488_ap_return_58,
        ap_return_59 => grp_em2calo_drvals_525_s_fu_488_ap_return_59,
        ap_return_60 => grp_em2calo_drvals_525_s_fu_488_ap_return_60,
        ap_return_61 => grp_em2calo_drvals_525_s_fu_488_ap_return_61,
        ap_return_62 => grp_em2calo_drvals_525_s_fu_488_ap_return_62,
        ap_return_63 => grp_em2calo_drvals_525_s_fu_488_ap_return_63,
        ap_return_64 => grp_em2calo_drvals_525_s_fu_488_ap_return_64,
        ap_return_65 => grp_em2calo_drvals_525_s_fu_488_ap_return_65,
        ap_return_66 => grp_em2calo_drvals_525_s_fu_488_ap_return_66,
        ap_return_67 => grp_em2calo_drvals_525_s_fu_488_ap_return_67,
        ap_return_68 => grp_em2calo_drvals_525_s_fu_488_ap_return_68,
        ap_return_69 => grp_em2calo_drvals_525_s_fu_488_ap_return_69,
        ap_return_70 => grp_em2calo_drvals_525_s_fu_488_ap_return_70,
        ap_return_71 => grp_em2calo_drvals_525_s_fu_488_ap_return_71,
        ap_return_72 => grp_em2calo_drvals_525_s_fu_488_ap_return_72,
        ap_return_73 => grp_em2calo_drvals_525_s_fu_488_ap_return_73,
        ap_return_74 => grp_em2calo_drvals_525_s_fu_488_ap_return_74,
        ap_return_75 => grp_em2calo_drvals_525_s_fu_488_ap_return_75,
        ap_return_76 => grp_em2calo_drvals_525_s_fu_488_ap_return_76,
        ap_return_77 => grp_em2calo_drvals_525_s_fu_488_ap_return_77,
        ap_return_78 => grp_em2calo_drvals_525_s_fu_488_ap_return_78,
        ap_return_79 => grp_em2calo_drvals_525_s_fu_488_ap_return_79,
        ap_return_80 => grp_em2calo_drvals_525_s_fu_488_ap_return_80,
        ap_return_81 => grp_em2calo_drvals_525_s_fu_488_ap_return_81,
        ap_return_82 => grp_em2calo_drvals_525_s_fu_488_ap_return_82,
        ap_return_83 => grp_em2calo_drvals_525_s_fu_488_ap_return_83,
        ap_return_84 => grp_em2calo_drvals_525_s_fu_488_ap_return_84,
        ap_return_85 => grp_em2calo_drvals_525_s_fu_488_ap_return_85,
        ap_return_86 => grp_em2calo_drvals_525_s_fu_488_ap_return_86,
        ap_return_87 => grp_em2calo_drvals_525_s_fu_488_ap_return_87,
        ap_return_88 => grp_em2calo_drvals_525_s_fu_488_ap_return_88,
        ap_return_89 => grp_em2calo_drvals_525_s_fu_488_ap_return_89,
        ap_return_90 => grp_em2calo_drvals_525_s_fu_488_ap_return_90,
        ap_return_91 => grp_em2calo_drvals_525_s_fu_488_ap_return_91,
        ap_return_92 => grp_em2calo_drvals_525_s_fu_488_ap_return_92,
        ap_return_93 => grp_em2calo_drvals_525_s_fu_488_ap_return_93,
        ap_return_94 => grp_em2calo_drvals_525_s_fu_488_ap_return_94,
        ap_return_95 => grp_em2calo_drvals_525_s_fu_488_ap_return_95,
        ap_return_96 => grp_em2calo_drvals_525_s_fu_488_ap_return_96,
        ap_return_97 => grp_em2calo_drvals_525_s_fu_488_ap_return_97,
        ap_return_98 => grp_em2calo_drvals_525_s_fu_488_ap_return_98,
        ap_return_99 => grp_em2calo_drvals_525_s_fu_488_ap_return_99);

    grp_pick_closest_1_fu_612 : component pick_closest_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_pick_closest_1_fu_612_ap_start,
        ap_done => grp_pick_closest_1_fu_612_ap_done,
        ap_idle => grp_pick_closest_1_fu_612_ap_idle,
        ap_ready => grp_pick_closest_1_fu_612_ap_ready,
        calo_track_drval_0_0_V_read => drvals_0_0_V_reg_1196,
        calo_track_drval_0_1_V_read => drvals_0_1_V_reg_1201,
        calo_track_drval_0_2_V_read => drvals_0_2_V_reg_1206,
        calo_track_drval_0_3_V_read => drvals_0_3_V_reg_1211,
        calo_track_drval_0_4_V_read => drvals_0_4_V_reg_1216,
        calo_track_drval_0_5_V_read => drvals_0_5_V_reg_1221,
        calo_track_drval_0_6_V_read => drvals_0_6_V_reg_1226,
        calo_track_drval_0_7_V_read => drvals_0_7_V_reg_1231,
        calo_track_drval_0_8_V_read => drvals_0_8_V_reg_1236,
        calo_track_drval_0_9_V_read => drvals_0_9_V_reg_1241,
        calo_track_drval_1_0_V_read => drvals_1_0_V_reg_1246,
        calo_track_drval_1_1_V_read => drvals_1_1_V_reg_1251,
        calo_track_drval_1_2_V_read => drvals_1_2_V_reg_1256,
        calo_track_drval_1_3_V_read => drvals_1_3_V_reg_1261,
        calo_track_drval_1_4_V_read => drvals_1_4_V_reg_1266,
        calo_track_drval_1_5_V_read => drvals_1_5_V_reg_1271,
        calo_track_drval_1_6_V_read => drvals_1_6_V_reg_1276,
        calo_track_drval_1_7_V_read => drvals_1_7_V_reg_1281,
        calo_track_drval_1_8_V_read => drvals_1_8_V_reg_1286,
        calo_track_drval_1_9_V_read => drvals_1_9_V_reg_1291,
        calo_track_drval_2_0_V_read => drvals_2_0_V_reg_1296,
        calo_track_drval_2_1_V_read => drvals_2_1_V_reg_1301,
        calo_track_drval_2_2_V_read => drvals_2_2_V_reg_1306,
        calo_track_drval_2_3_V_read => drvals_2_3_V_reg_1311,
        calo_track_drval_2_4_V_read => drvals_2_4_V_reg_1316,
        calo_track_drval_2_5_V_read => drvals_2_5_V_reg_1321,
        calo_track_drval_2_6_V_read => drvals_2_6_V_reg_1326,
        calo_track_drval_2_7_V_read => drvals_2_7_V_reg_1331,
        calo_track_drval_2_8_V_read => drvals_2_8_V_reg_1336,
        calo_track_drval_2_9_V_read => drvals_2_9_V_reg_1341,
        calo_track_drval_3_0_V_read => drvals_3_0_V_reg_1346,
        calo_track_drval_3_1_V_read => drvals_3_1_V_reg_1351,
        calo_track_drval_3_2_V_read => drvals_3_2_V_reg_1356,
        calo_track_drval_3_3_V_read => drvals_3_3_V_reg_1361,
        calo_track_drval_3_4_V_read => drvals_3_4_V_reg_1366,
        calo_track_drval_3_5_V_read => drvals_3_5_V_reg_1371,
        calo_track_drval_3_6_V_read => drvals_3_6_V_reg_1376,
        calo_track_drval_3_7_V_read => drvals_3_7_V_reg_1381,
        calo_track_drval_3_8_V_read => drvals_3_8_V_reg_1386,
        calo_track_drval_3_9_V_read => drvals_3_9_V_reg_1391,
        calo_track_drval_4_0_V_read => drvals_4_0_V_reg_1396,
        calo_track_drval_4_1_V_read => drvals_4_1_V_reg_1401,
        calo_track_drval_4_2_V_read => drvals_4_2_V_reg_1406,
        calo_track_drval_4_3_V_read => drvals_4_3_V_reg_1411,
        calo_track_drval_4_4_V_read => drvals_4_4_V_reg_1416,
        calo_track_drval_4_5_V_read => drvals_4_5_V_reg_1421,
        calo_track_drval_4_6_V_read => drvals_4_6_V_reg_1426,
        calo_track_drval_4_7_V_read => drvals_4_7_V_reg_1431,
        calo_track_drval_4_8_V_read => drvals_4_8_V_reg_1436,
        calo_track_drval_4_9_V_read => drvals_4_9_V_reg_1441,
        calo_track_drval_5_0_V_read => drvals_5_0_V_reg_1446,
        calo_track_drval_5_1_V_read => drvals_5_1_V_reg_1451,
        calo_track_drval_5_2_V_read => drvals_5_2_V_reg_1456,
        calo_track_drval_5_3_V_read => drvals_5_3_V_reg_1461,
        calo_track_drval_5_4_V_read => drvals_5_4_V_reg_1466,
        calo_track_drval_5_5_V_read => drvals_5_5_V_reg_1471,
        calo_track_drval_5_6_V_read => drvals_5_6_V_reg_1476,
        calo_track_drval_5_7_V_read => drvals_5_7_V_reg_1481,
        calo_track_drval_5_8_V_read => drvals_5_8_V_reg_1486,
        calo_track_drval_5_9_V_read => drvals_5_9_V_reg_1491,
        calo_track_drval_6_0_V_read => drvals_6_0_V_reg_1496,
        calo_track_drval_6_1_V_read => drvals_6_1_V_reg_1501,
        calo_track_drval_6_2_V_read => drvals_6_2_V_reg_1506,
        calo_track_drval_6_3_V_read => drvals_6_3_V_reg_1511,
        calo_track_drval_6_4_V_read => drvals_6_4_V_reg_1516,
        calo_track_drval_6_5_V_read => drvals_6_5_V_reg_1521,
        calo_track_drval_6_6_V_read => drvals_6_6_V_reg_1526,
        calo_track_drval_6_7_V_read => drvals_6_7_V_reg_1531,
        calo_track_drval_6_8_V_read => drvals_6_8_V_reg_1536,
        calo_track_drval_6_9_V_read => drvals_6_9_V_reg_1541,
        calo_track_drval_7_0_V_read => drvals_7_0_V_reg_1546,
        calo_track_drval_7_1_V_read => drvals_7_1_V_reg_1551,
        calo_track_drval_7_2_V_read => drvals_7_2_V_reg_1556,
        calo_track_drval_7_3_V_read => drvals_7_3_V_reg_1561,
        calo_track_drval_7_4_V_read => drvals_7_4_V_reg_1566,
        calo_track_drval_7_5_V_read => drvals_7_5_V_reg_1571,
        calo_track_drval_7_6_V_read => drvals_7_6_V_reg_1576,
        calo_track_drval_7_7_V_read => drvals_7_7_V_reg_1581,
        calo_track_drval_7_8_V_read => drvals_7_8_V_reg_1586,
        calo_track_drval_7_9_V_read => drvals_7_9_V_reg_1591,
        calo_track_drval_8_0_V_read => drvals_8_0_V_reg_1596,
        calo_track_drval_8_1_V_read => drvals_8_1_V_reg_1601,
        calo_track_drval_8_2_V_read => drvals_8_2_V_reg_1606,
        calo_track_drval_8_3_V_read => drvals_8_3_V_reg_1611,
        calo_track_drval_8_4_V_read => drvals_8_4_V_reg_1616,
        calo_track_drval_8_5_V_read => drvals_8_5_V_reg_1621,
        calo_track_drval_8_6_V_read => drvals_8_6_V_reg_1626,
        calo_track_drval_8_7_V_read => drvals_8_7_V_reg_1631,
        calo_track_drval_8_8_V_read => drvals_8_8_V_reg_1636,
        calo_track_drval_8_9_V_read => drvals_8_9_V_reg_1641,
        calo_track_drval_9_0_V_read => drvals_9_0_V_reg_1646,
        calo_track_drval_9_1_V_read => drvals_9_1_V_reg_1651,
        calo_track_drval_9_2_V_read => drvals_9_2_V_reg_1656,
        calo_track_drval_9_3_V_read => drvals_9_3_V_reg_1661,
        calo_track_drval_9_4_V_read => drvals_9_4_V_reg_1666,
        calo_track_drval_9_5_V_read => drvals_9_5_V_reg_1671,
        calo_track_drval_9_6_V_read => drvals_9_6_V_reg_1676,
        calo_track_drval_9_7_V_read => drvals_9_7_V_reg_1681,
        calo_track_drval_9_8_V_read => drvals_9_8_V_reg_1686,
        calo_track_drval_9_9_V_read => drvals_9_9_V_reg_1691,
        ap_return_0 => grp_pick_closest_1_fu_612_ap_return_0,
        ap_return_1 => grp_pick_closest_1_fu_612_ap_return_1,
        ap_return_2 => grp_pick_closest_1_fu_612_ap_return_2,
        ap_return_3 => grp_pick_closest_1_fu_612_ap_return_3,
        ap_return_4 => grp_pick_closest_1_fu_612_ap_return_4,
        ap_return_5 => grp_pick_closest_1_fu_612_ap_return_5,
        ap_return_6 => grp_pick_closest_1_fu_612_ap_return_6,
        ap_return_7 => grp_pick_closest_1_fu_612_ap_return_7,
        ap_return_8 => grp_pick_closest_1_fu_612_ap_return_8,
        ap_return_9 => grp_pick_closest_1_fu_612_ap_return_9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_pick_closest_1_fu_612_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_pick_closest_1_fu_612_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then 
                    grp_pick_closest_1_fu_612_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_pick_closest_1_fu_612_ap_ready = ap_const_logic_1)) then 
                    grp_pick_closest_1_fu_612_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001))) then
                drvals_0_0_V_reg_1196 <= grp_em2calo_drvals_525_s_fu_488_ap_return_0;
                drvals_0_1_V_reg_1201 <= grp_em2calo_drvals_525_s_fu_488_ap_return_1;
                drvals_0_2_V_reg_1206 <= grp_em2calo_drvals_525_s_fu_488_ap_return_2;
                drvals_0_3_V_reg_1211 <= grp_em2calo_drvals_525_s_fu_488_ap_return_3;
                drvals_0_4_V_reg_1216 <= grp_em2calo_drvals_525_s_fu_488_ap_return_4;
                drvals_0_5_V_reg_1221 <= grp_em2calo_drvals_525_s_fu_488_ap_return_5;
                drvals_0_6_V_reg_1226 <= grp_em2calo_drvals_525_s_fu_488_ap_return_6;
                drvals_0_7_V_reg_1231 <= grp_em2calo_drvals_525_s_fu_488_ap_return_7;
                drvals_0_8_V_reg_1236 <= grp_em2calo_drvals_525_s_fu_488_ap_return_8;
                drvals_0_9_V_reg_1241 <= grp_em2calo_drvals_525_s_fu_488_ap_return_9;
                drvals_1_0_V_reg_1246 <= grp_em2calo_drvals_525_s_fu_488_ap_return_10;
                drvals_1_1_V_reg_1251 <= grp_em2calo_drvals_525_s_fu_488_ap_return_11;
                drvals_1_2_V_reg_1256 <= grp_em2calo_drvals_525_s_fu_488_ap_return_12;
                drvals_1_3_V_reg_1261 <= grp_em2calo_drvals_525_s_fu_488_ap_return_13;
                drvals_1_4_V_reg_1266 <= grp_em2calo_drvals_525_s_fu_488_ap_return_14;
                drvals_1_5_V_reg_1271 <= grp_em2calo_drvals_525_s_fu_488_ap_return_15;
                drvals_1_6_V_reg_1276 <= grp_em2calo_drvals_525_s_fu_488_ap_return_16;
                drvals_1_7_V_reg_1281 <= grp_em2calo_drvals_525_s_fu_488_ap_return_17;
                drvals_1_8_V_reg_1286 <= grp_em2calo_drvals_525_s_fu_488_ap_return_18;
                drvals_1_9_V_reg_1291 <= grp_em2calo_drvals_525_s_fu_488_ap_return_19;
                drvals_2_0_V_reg_1296 <= grp_em2calo_drvals_525_s_fu_488_ap_return_20;
                drvals_2_1_V_reg_1301 <= grp_em2calo_drvals_525_s_fu_488_ap_return_21;
                drvals_2_2_V_reg_1306 <= grp_em2calo_drvals_525_s_fu_488_ap_return_22;
                drvals_2_3_V_reg_1311 <= grp_em2calo_drvals_525_s_fu_488_ap_return_23;
                drvals_2_4_V_reg_1316 <= grp_em2calo_drvals_525_s_fu_488_ap_return_24;
                drvals_2_5_V_reg_1321 <= grp_em2calo_drvals_525_s_fu_488_ap_return_25;
                drvals_2_6_V_reg_1326 <= grp_em2calo_drvals_525_s_fu_488_ap_return_26;
                drvals_2_7_V_reg_1331 <= grp_em2calo_drvals_525_s_fu_488_ap_return_27;
                drvals_2_8_V_reg_1336 <= grp_em2calo_drvals_525_s_fu_488_ap_return_28;
                drvals_2_9_V_reg_1341 <= grp_em2calo_drvals_525_s_fu_488_ap_return_29;
                drvals_3_0_V_reg_1346 <= grp_em2calo_drvals_525_s_fu_488_ap_return_30;
                drvals_3_1_V_reg_1351 <= grp_em2calo_drvals_525_s_fu_488_ap_return_31;
                drvals_3_2_V_reg_1356 <= grp_em2calo_drvals_525_s_fu_488_ap_return_32;
                drvals_3_3_V_reg_1361 <= grp_em2calo_drvals_525_s_fu_488_ap_return_33;
                drvals_3_4_V_reg_1366 <= grp_em2calo_drvals_525_s_fu_488_ap_return_34;
                drvals_3_5_V_reg_1371 <= grp_em2calo_drvals_525_s_fu_488_ap_return_35;
                drvals_3_6_V_reg_1376 <= grp_em2calo_drvals_525_s_fu_488_ap_return_36;
                drvals_3_7_V_reg_1381 <= grp_em2calo_drvals_525_s_fu_488_ap_return_37;
                drvals_3_8_V_reg_1386 <= grp_em2calo_drvals_525_s_fu_488_ap_return_38;
                drvals_3_9_V_reg_1391 <= grp_em2calo_drvals_525_s_fu_488_ap_return_39;
                drvals_4_0_V_reg_1396 <= grp_em2calo_drvals_525_s_fu_488_ap_return_40;
                drvals_4_1_V_reg_1401 <= grp_em2calo_drvals_525_s_fu_488_ap_return_41;
                drvals_4_2_V_reg_1406 <= grp_em2calo_drvals_525_s_fu_488_ap_return_42;
                drvals_4_3_V_reg_1411 <= grp_em2calo_drvals_525_s_fu_488_ap_return_43;
                drvals_4_4_V_reg_1416 <= grp_em2calo_drvals_525_s_fu_488_ap_return_44;
                drvals_4_5_V_reg_1421 <= grp_em2calo_drvals_525_s_fu_488_ap_return_45;
                drvals_4_6_V_reg_1426 <= grp_em2calo_drvals_525_s_fu_488_ap_return_46;
                drvals_4_7_V_reg_1431 <= grp_em2calo_drvals_525_s_fu_488_ap_return_47;
                drvals_4_8_V_reg_1436 <= grp_em2calo_drvals_525_s_fu_488_ap_return_48;
                drvals_4_9_V_reg_1441 <= grp_em2calo_drvals_525_s_fu_488_ap_return_49;
                drvals_5_0_V_reg_1446 <= grp_em2calo_drvals_525_s_fu_488_ap_return_50;
                drvals_5_1_V_reg_1451 <= grp_em2calo_drvals_525_s_fu_488_ap_return_51;
                drvals_5_2_V_reg_1456 <= grp_em2calo_drvals_525_s_fu_488_ap_return_52;
                drvals_5_3_V_reg_1461 <= grp_em2calo_drvals_525_s_fu_488_ap_return_53;
                drvals_5_4_V_reg_1466 <= grp_em2calo_drvals_525_s_fu_488_ap_return_54;
                drvals_5_5_V_reg_1471 <= grp_em2calo_drvals_525_s_fu_488_ap_return_55;
                drvals_5_6_V_reg_1476 <= grp_em2calo_drvals_525_s_fu_488_ap_return_56;
                drvals_5_7_V_reg_1481 <= grp_em2calo_drvals_525_s_fu_488_ap_return_57;
                drvals_5_8_V_reg_1486 <= grp_em2calo_drvals_525_s_fu_488_ap_return_58;
                drvals_5_9_V_reg_1491 <= grp_em2calo_drvals_525_s_fu_488_ap_return_59;
                drvals_6_0_V_reg_1496 <= grp_em2calo_drvals_525_s_fu_488_ap_return_60;
                drvals_6_1_V_reg_1501 <= grp_em2calo_drvals_525_s_fu_488_ap_return_61;
                drvals_6_2_V_reg_1506 <= grp_em2calo_drvals_525_s_fu_488_ap_return_62;
                drvals_6_3_V_reg_1511 <= grp_em2calo_drvals_525_s_fu_488_ap_return_63;
                drvals_6_4_V_reg_1516 <= grp_em2calo_drvals_525_s_fu_488_ap_return_64;
                drvals_6_5_V_reg_1521 <= grp_em2calo_drvals_525_s_fu_488_ap_return_65;
                drvals_6_6_V_reg_1526 <= grp_em2calo_drvals_525_s_fu_488_ap_return_66;
                drvals_6_7_V_reg_1531 <= grp_em2calo_drvals_525_s_fu_488_ap_return_67;
                drvals_6_8_V_reg_1536 <= grp_em2calo_drvals_525_s_fu_488_ap_return_68;
                drvals_6_9_V_reg_1541 <= grp_em2calo_drvals_525_s_fu_488_ap_return_69;
                drvals_7_0_V_reg_1546 <= grp_em2calo_drvals_525_s_fu_488_ap_return_70;
                drvals_7_1_V_reg_1551 <= grp_em2calo_drvals_525_s_fu_488_ap_return_71;
                drvals_7_2_V_reg_1556 <= grp_em2calo_drvals_525_s_fu_488_ap_return_72;
                drvals_7_3_V_reg_1561 <= grp_em2calo_drvals_525_s_fu_488_ap_return_73;
                drvals_7_4_V_reg_1566 <= grp_em2calo_drvals_525_s_fu_488_ap_return_74;
                drvals_7_5_V_reg_1571 <= grp_em2calo_drvals_525_s_fu_488_ap_return_75;
                drvals_7_6_V_reg_1576 <= grp_em2calo_drvals_525_s_fu_488_ap_return_76;
                drvals_7_7_V_reg_1581 <= grp_em2calo_drvals_525_s_fu_488_ap_return_77;
                drvals_7_8_V_reg_1586 <= grp_em2calo_drvals_525_s_fu_488_ap_return_78;
                drvals_7_9_V_reg_1591 <= grp_em2calo_drvals_525_s_fu_488_ap_return_79;
                drvals_8_0_V_reg_1596 <= grp_em2calo_drvals_525_s_fu_488_ap_return_80;
                drvals_8_1_V_reg_1601 <= grp_em2calo_drvals_525_s_fu_488_ap_return_81;
                drvals_8_2_V_reg_1606 <= grp_em2calo_drvals_525_s_fu_488_ap_return_82;
                drvals_8_3_V_reg_1611 <= grp_em2calo_drvals_525_s_fu_488_ap_return_83;
                drvals_8_4_V_reg_1616 <= grp_em2calo_drvals_525_s_fu_488_ap_return_84;
                drvals_8_5_V_reg_1621 <= grp_em2calo_drvals_525_s_fu_488_ap_return_85;
                drvals_8_6_V_reg_1626 <= grp_em2calo_drvals_525_s_fu_488_ap_return_86;
                drvals_8_7_V_reg_1631 <= grp_em2calo_drvals_525_s_fu_488_ap_return_87;
                drvals_8_8_V_reg_1636 <= grp_em2calo_drvals_525_s_fu_488_ap_return_88;
                drvals_8_9_V_reg_1641 <= grp_em2calo_drvals_525_s_fu_488_ap_return_89;
                drvals_9_0_V_reg_1646 <= grp_em2calo_drvals_525_s_fu_488_ap_return_90;
                drvals_9_1_V_reg_1651 <= grp_em2calo_drvals_525_s_fu_488_ap_return_91;
                drvals_9_2_V_reg_1656 <= grp_em2calo_drvals_525_s_fu_488_ap_return_92;
                drvals_9_3_V_reg_1661 <= grp_em2calo_drvals_525_s_fu_488_ap_return_93;
                drvals_9_4_V_reg_1666 <= grp_em2calo_drvals_525_s_fu_488_ap_return_94;
                drvals_9_5_V_reg_1671 <= grp_em2calo_drvals_525_s_fu_488_ap_return_95;
                drvals_9_6_V_reg_1676 <= grp_em2calo_drvals_525_s_fu_488_ap_return_96;
                drvals_9_7_V_reg_1681 <= grp_em2calo_drvals_525_s_fu_488_ap_return_97;
                drvals_9_8_V_reg_1686 <= grp_em2calo_drvals_525_s_fu_488_ap_return_98;
                drvals_9_9_V_reg_1691 <= grp_em2calo_drvals_525_s_fu_488_ap_return_99;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage5_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to2, ap_block_pp0_stage1_subdone, ap_reset_idle_pp0, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage3_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage4_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage5_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage2_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage4_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage5_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001)) or ((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_pick_closest_1_fu_612_ap_return_0;
    ap_return_1 <= grp_pick_closest_1_fu_612_ap_return_1;
    ap_return_2 <= grp_pick_closest_1_fu_612_ap_return_2;
    ap_return_3 <= grp_pick_closest_1_fu_612_ap_return_3;
    ap_return_4 <= grp_pick_closest_1_fu_612_ap_return_4;
    ap_return_5 <= grp_pick_closest_1_fu_612_ap_return_5;
    ap_return_6 <= grp_pick_closest_1_fu_612_ap_return_6;
    ap_return_7 <= grp_pick_closest_1_fu_612_ap_return_7;
    ap_return_8 <= grp_pick_closest_1_fu_612_ap_return_8;
    ap_return_9 <= grp_pick_closest_1_fu_612_ap_return_9;

    grp_em2calo_drvals_525_s_fu_488_ap_start_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start = ap_const_logic_1))) then 
            grp_em2calo_drvals_525_s_fu_488_ap_start <= ap_const_logic_1;
        else 
            grp_em2calo_drvals_525_s_fu_488_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_pick_closest_1_fu_612_ap_start <= grp_pick_closest_1_fu_612_ap_start_reg;
end behav;
